const DB_NAME='nightshade-forge';const DB_VERSION=1;const STORE='vault';let db;let state={locked:true,tab:'home'};const $=s=>document.querySelector(s);
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE)};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function get(key){return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(key,val){return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(val,key);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function del(key){return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).delete(key);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function hashPin(pin,salt){const data=new TextEncoder().encode(salt+pin);const h=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function createPin(pin){const salt=crypto.randomUUID();await put('security',{salt,verifier:await hashPin(pin,salt),ageConfirmed:true});sessionStorage.setItem('nf_unlocked','1');state.locked=false;render()}
async function verifyPin(pin){const s=await get('security');if(!s)return false;return (await hashPin(pin,s.salt))===s.verifier}
function ageGate(){return `<main class="shell"><div class="hero"><div class="brand">Nightshade Forge</div><h1>Private creative space.</h1><p class="muted">A local-first roleplay and writing studio. Your characters, conversations and memories stay in this browser unless you deliberately connect an external generation service.</p></div><section class="card stack"><h2>Age confirmation</h2><p class="muted">This app is intended for adults 18 and over.</p><button class="btn primary" id="age">I am 18 or older</button></section></main>`}
function pinSetup(){return `<main class="shell"><div class="hero"><div class="brand">Nightshade Forge</div><h1>Choose your access code.</h1><p class="muted">Pick any four digits. The raw code is never stored.</p></div><section class="card stack"><input id="p1" class="input pin" inputmode="numeric" maxlength="4" type="password" placeholder="••••"><input id="p2" class="input pin" inputmode="numeric" maxlength="4" type="password" placeholder="confirm"><button class="btn primary" id="savepin">Lock the Forge</button><div id="msg" class="muted"></div></section></main>`}
function lockScreen(){return `<main class="shell"><div class="hero"><div class="brand">Nightshade Forge</div><h1>Forge locked.</h1></div><section class="card stack"><input id="unlock" class="input pin" inputmode="numeric" maxlength="4" type="password" placeholder="••••"><button class="btn primary" id="unlockBtn">Unlock</button><div id="msg" class="muted"></div></section></main>`}
function nav(){return `<nav class="nav">${[['home','⌂','Chats'],['chars','♢','Characters'],['create','＋','Create'],['vault','▦','Vault'],['settings','⚙','Settings']].map(([k,i,t])=>`<button class="${state.tab===k?'active':''}" data-tab="${k}">${i}<br><small>${t}</small></button>`).join('')}</nav>`}
function home(){return `<main class="shell"><div class="hero"><div class="brand">Nightshade Forge</div><h1>Your private forge.</h1><p class="muted">The foundation is live. Everything here is saved locally.</p></div><section class="card stack"><div class="row"><span class="pill">LOCAL-FIRST</span><span class="pill">PIN LOCKED</span></div><h2>Start building</h2><p class="muted">Create characters, then we'll layer in chat, memory, voices and provider connections.</p><button class="btn primary" data-tab="create">Create a character</button><div class="notice">Demo generation and external model connections will be added as separate adapters. Local data remains yours.</div></section>${nav()}</main>`}
function chars(){return `<main class="shell"><div class="hero"><div class="brand">Characters</div><h1>Character Forge</h1><p class="muted">Your cast will live here, locally.</p></div><section class="card stack"><input id="charName" class="input" placeholder="Character name"><textarea id="charBio" class="input" rows="5" placeholder="Personality, backstory, scenario..."></textarea><button class="btn primary" id="saveChar">Save character</button><div id="charMsg" class="muted"></div></section>${nav()}</main>`}
function create(){return chars().replace('Character Forge','Create Character').replace('Characters</div>','Create</div>')}
async function vault(){const sec=await get('security');const ch=await get('characters')||[];const chats=await get('conversations')||[];return `<main class="shell"><div class="hero"><div class="brand">Data Vault</div><h1>Local data</h1><p class="muted">Nothing here requires a cloud account.</p></div><section class="card"><div class="vault-item"><span>Characters</span><strong>${ch.length}</strong></div><div class="vault-item"><span>Conversations</span><strong>${chats.length}</strong></div><div class="vault-item"><span>Security</span><strong>${sec?'configured':'not set'}</strong></div><div class="stack" style="margin-top:16px"><button class="btn" id="export">Export backup</button><button class="btn danger" id="erase">Delete everything</button></div><div id="vaultMsg" class="muted" style="margin-top:10px"></div></section>${nav()}</main>`}
function settings(){return `<main class="shell"><div class="hero"><div class="brand">Settings</div><h1>Control the Forge.</h1></div><section class="card stack"><button class="btn" id="lock">Lock now</button><button class="btn" id="changePin">Change PIN</button><div class="notice">Auto-lock and provider settings will be added in the next passes.</div></section>${nav()}</main>`}
async function render(){const root=$('#app');if(!(await get('security'))){root.innerHTML=ageGate();$('#age').onclick=async()=>{await put('security',{ageConfirmed:true,setupNeeded:true});render()};return}const sec=await get('security');if(sec.setupNeeded){root.innerHTML=pinSetup();$('#savepin').onclick=async()=>{const a=$('#p1').value,b=$('#p2').value;const m=$('#msg');if(!/^\d{4}$/.test(a)||a!==b){m.textContent='Enter the same four digits in both fields.';return}await createPin(a)};return}if(sessionStorage.getItem('nf_unlocked')!=='1'||state.locked){root.innerHTML=lockScreen();$('#unlockBtn').onclick=async()=>{const ok=await verifyPin($('#unlock').value);if(!ok){$('#msg').textContent='Incorrect code.';return}sessionStorage.setItem('nf_unlocked','1');state.locked=false;render()};return}if(state.tab==='home')root.innerHTML=home();else if(state.tab==='chars')root.innerHTML=chars();else if(state.tab==='create')root.innerHTML=create();else if(state.tab==='vault')root.innerHTML=await vault();else root.innerHTML=settings();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});const save=$('#saveChar');if(save)save.onclick=async()=>{const arr=await get('characters')||[];arr.push({id:crypto.randomUUID(),name:$('#charName').value||'Unnamed',bio:$('#charBio').value||'',createdAt:new Date().toISOString()});await put('characters',arr);$('#charMsg').textContent='Saved locally.'};const exp=$('#export');if(exp)exp.onclick=async()=>{const payload={version:1,exportedAt:new Date().toISOString(),security:{ageConfirmed:true},characters:await get('characters')||[],conversations:await get('conversations')||[],settings:await get('settings')||{}};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='nightshade-forge-backup.json';a.click();URL.revokeObjectURL(a.href)};const erase=$('#erase');if(erase)erase.onclick=async()=>{const p=prompt('Enter your 4-digit code to erase local data.');if(p&&await verifyPin(p)){const keys=['characters','conversations','settings','security'];for(const k of keys)await del(k);sessionStorage.clear();location.reload()}else $('#vaultMsg').textContent='Not erased.'};const lock=$('#lock');if(lock)lock.onclick=()=>{sessionStorage.removeItem('nf_unlocked');state.locked=true;render()};const cp=$('#changePin');if(cp)cp.onclick=async()=>{const old=prompt('Current 4-digit code');if(!(await verifyPin(old||''))){alert('Incorrect code.');return}const n=prompt('New 4-digit code');if(!/^\d{4}$/.test(n||'')){alert('Code must be four digits.');return}const s=await get('security');s.salt=crypto.randomUUID();s.verifier=await hashPin(n,s.salt);await put('security',s);alert('PIN changed.')}}
(async()=>{await openDB();render();setInterval(()=>{if(sessionStorage.getItem('nf_unlocked')==='1'&&document.hidden){/* placeholder for future inactivity timer */}},15000)})();