(()=>{
const KEY='nf_character_state';
const defaults=()=>({mood:'Neutral',relationship:'Unspecified',activity:'Idle',goals:[],secrets:[],plotThreads:[],updatedAt:new Date().toISOString()});
async function all(){return await get(KEY)||{}}
async function stateFor(id){const a=await all();return {...defaults(),...(a[id]||{})}}
async function save(id,v){const a=await all();a[id]={...await stateFor(id),...v,updatedAt:new Date().toISOString()};await put(KEY,a);return a[id]}
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function list(v){return (Array.isArray(v)?v:[]).filter(Boolean).map(x=>String(x).trim()).filter(Boolean)}
async function character(){const cs=await get('characters')||[];return cs.find(c=>c.id===state.chat)}
async function activeConv(){const a=await get('conversations')||[];return a.find(x=>x.id===state.nfConversationId)||a.find(x=>x.characterId===state.chat)}
function moodTone(m){m=String(m||'').toLowerCase();return m.includes('angry')||m.includes('hostile')||m.includes('danger')?'⚠':m.includes('happy')||m.includes('excited')||m.includes('calm')?'✦':'◌'}
async function decorate(){if(state.tab!=='chat'||!state.chat)return;const c=await character();if(!c)return;const x=await activeConv();const s=await stateFor(c.id);const head=document.querySelector('.chathead');if(!head)return;document.querySelector('#nfStateStrip')?.remove();const strip=document.createElement('div');strip.id='nfStateStrip';strip.className='nf-state-strip';const chips=[`${moodTone(s.mood)} ${s.mood}`,`♡ ${s.relationship}`,`⌁ ${s.activity}`];if(s.goals.length)chips.push(`◎ ${s.goals.length} goal${s.goals.length===1?'':'s'}`);if(s.plotThreads.length)chips.push(`◈ ${s.plotThreads.length} thread${s.plotThreads.length===1?'':'s'}`);chips.forEach(t=>{const b=document.createElement('button');b.className='nf-state-chip';b.textContent=t;b.title='Character state';b.onclick=()=>openEditor(c.id);strip.append(b)});head.insertAdjacentElement('afterend',strip)}
async function openEditor(id){const s=await stateFor(id);const mood=prompt('Current mood',s.mood);if(mood===null)return;const relationship=prompt('Relationship state',s.relationship);if(relationship===null)return;const activity=prompt('Current activity',s.activity);if(activity===null)return;const goals=prompt('Goals — separate with commas',s.goals.join(', '));if(goals===null)return;const secrets=prompt('Secrets — separate with commas',s.secrets.join(', '));if(secrets===null)return;const threads=prompt('Plot threads — separate with commas',s.plotThreads.join(', '));if(threads===null)return;await save(id,{mood:mood.trim()||'Neutral',relationship:relationship.trim()||'Unspecified',activity:activity.trim()||'Idle',goals:list(goals.split(',')),secrets:list(secrets.split(',')),plotThreads:list(threads.split(','))});await render()}
async function injectPrompt(){const old=window.fetch;if(window.__nfStateFetch)return;window.__nfStateFetch=true;window.fetch=async function(input,init){try{if(init?.body&&typeof init.body==='string'){const j=JSON.parse(init.body);if(Array.isArray(j.messages)){const sys=j.messages.find(m=>m.role==='system');if(sys&&state.chat){const c=await character(),s=await stateFor(state.chat);if(c){sys.content+='\n\n[CURRENT CHARACTER STATE — MAINTAIN CONTINUITY]\nMood: '+s.mood+'\nRelationship: '+s.relationship+'\nCurrent activity: '+s.activity+'\nGoals: '+(s.goals.join('; ')||'none')+'\nPlot threads: '+(s.plotThreads.join('; ')||'none')+'\nPrivate character secrets (do not reveal unless naturally appropriate): '+(s.secrets.join('; ')||'none')}}init.body=JSON.stringify(j)}}}catch(e){}return old.apply(this,arguments)}}
injectPrompt();
window.nfCharacterState={stateFor,save,openEditor};
const oldRender=window.render;window.render=async()=>{await oldRender();await decorate()};window.addEventListener('load',()=>setTimeout(decorate,0));
const style=document.createElement('style');style.textContent='.nf-state-strip{display:flex;gap:6px;padding:5px 8px 7px;overflow:auto;border-bottom:1px solid #24182a;background:#0e0a12}.nf-state-chip{white-space:nowrap;border:1px solid #38253d;background:#17101b;color:#d9cddd;border-radius:999px;padding:5px 9px;font-size:10px}.nf-state-chip:hover{border-color:#a94d8c;color:#ff83ca;background:#211426}@media(max-width:560px){.nf-state-strip{scrollbar-width:none}.nf-state-chip{font-size:9px;padding:5px 8px}}';document.head.append(style);
})();
