(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const uid=()=>crypto.randomUUID();
let openId=null;
const getC=async id=>(await get('characters')||[]).find(c=>c.id===id);
const saveC=async c=>{const cs=await get('characters')||[];const i=cs.findIndex(x=>x.id===c.id);if(i>=0)cs[i]=c;else cs.push(c);await put('characters',cs)};
function normalize(c){c.card=c.card||{};c.card.alternateGreetings=c.card.alternateGreetings||[];c.card.exampleDialogue=c.card.exampleDialogue||'';c.card.creator=c.card.creator||'';c.card.version=c.card.version||'';c.card.notes=c.card.notes||'';c.card.systemPrompt=c.card.systemPrompt||'';c.card.postHistoryInstructions=c.card.postHistoryInstructions||'';c.card.extensions=c.card.extensions||{};c.lorebook=Array.isArray(c.lorebook)?c.lorebook:[];return c}
function cardData(c){normalize(c);return {name:c.name||'',description:c.backstory||'',personality:c.personality||'',scenario:c.scenario||'',first_mes:c.greeting||'',alternate_greetings:c.card.alternateGreetings,system_prompt:c.card.systemPrompt,post_history_instructions:c.card.postHistoryInstructions,mes_example:c.card.exampleDialogue,creator_notes:c.card.notes,creator:c.card.creator,character_version:c.card.version,tags:c.tags||[],extensions:{...c.card.extensions,lorebook:c.lorebook}}}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportCard(c){download((c.name||'character').replace(/[^\w.-]+/g,'_')+'.json',JSON.stringify({spec:'chara_card_v2',spec_version:'2.0',data:cardData(c)},null,2))}
function exportLore(c){download((c.name||'character').replace(/[^\w.-]+/g,'_')+'_lorebook.json',JSON.stringify({name:c.name||'Lorebook',entries:c.lorebook||[]},null,2))}
function activeLore(c,messages){normalize(c);const text=(messages||[]).map(m=>m.text||'').join('\n').toLowerCase();return c.lorebook.filter(e=>e.enabled!==false&&Array.isArray(e.keys)&&e.keys.some(k=>k&&text.includes(String(k).toLowerCase()))).sort((a,b)=>(b.priority||0)-(a.priority||0)).slice(0,20)}
window.nfLoreContext=(c,messages)=>activeLore(c,messages).map(e=>`[LOREBOOK: ${e.name||'Entry'}]\n${e.content||''}`).join('\n\n');
function wrapPromptHook(){if(window.__nfLoreHook)return;window.__nfLoreHook=1;const old=window.realReply;if(typeof old!=='function')return;window.realReply=async function(...args){return old.apply(this,args)}}
function editor(c){normalize(c);const box=document.createElement('section');box.className='card stack';box.id='fullCardEditor';box.innerHTML=`<h2>Character Card</h2><p class="muted">Full Tavern / SillyTavern-compatible metadata and per-character lorebook.</p><label>Creator<input id="ccCreator" value="${esc(c.card.creator)}"></label><label>Version<input id="ccVersion" value="${esc(c.card.version)}"></label><label>Creator notes<textarea id="ccNotes">${esc(c.card.notes)}</textarea></label><label>System prompt<textarea id="ccSystem">${esc(c.card.systemPrompt)}</textarea></label><label>Post-history instructions<textarea id="ccPost">${esc(c.card.postHistoryInstructions)}</textarea></label><label>Example dialogue<textarea id="ccExample">${esc(c.card.exampleDialogue)}</textarea></label><label>Alternate greetings<textarea id="ccGreetings" placeholder="One greeting per line">${esc(c.card.alternateGreetings.join('\n'))}</textarea></label><div class="row wrap"><button class="btn" id="ccSave">Save card data</button><button class="btn" id="ccExport">Export JSON</button><button class="btn" id="ccLoreExport">Export lorebook</button></div><hr><h2>Lorebook</h2><div id="loreEntries"></div><button class="btn" id="loreAdd">＋ Add lore entry</button>`;box.querySelector('#ccSave').onclick=async()=>{c.card.creator=ccCreator.value;c.card.version=ccVersion.value;c.card.notes=ccNotes.value;c.card.systemPrompt=ccSystem.value;c.card.postHistoryInstructions=ccPost.value;c.card.exampleDialogue=ccExample.value;c.card.alternateGreetings=ccGreetings.value.split('\n').map(x=>x.trim()).filter(Boolean);await saveC(c);alert('Character card saved.')};box.querySelector('#ccExport').onclick=()=>exportCard(c);box.querySelector('#ccLoreExport').onclick=()=>exportLore(c);const list=box.querySelector('#loreEntries');const paint=()=>{list.innerHTML='';c.lorebook.forEach((e,i)=>{const d=document.createElement('div');d.className='card';d.innerHTML=`<strong>${esc(e.name||'Untitled')}</strong><div class="muted tiny">Keys: ${esc((e.keys||[]).join(', '))} · Priority: ${e.priority||0}</div><p>${esc(e.content||'')}</p><div class="row wrap"><button class="btn" data-edit-lore="${i}">Edit</button><button class="btn" data-del-lore="${i}">Delete</button></div>`;list.appendChild(d)});list.querySelectorAll('[data-del-lore]').forEach(b=>b.onclick=async()=>{c.lorebook.splice(+b.dataset.delLore,1);await saveC(c);paint()});list.querySelectorAll('[data-edit-lore]').forEach(b=>b.onclick=()=>loreForm(c,+b.dataset.editLore,paint))};box.querySelector('#loreAdd').onclick=()=>loreForm(c,-1,paint);paint();return box}
function loreForm(c,index,done){const old=index>=0?c.lorebook[index]:{name:'',keys:[],content:'',priority:0,enabled:true};const name=prompt('Lore entry name:',old.name||'');if(name===null)return;const keys=prompt('Trigger keywords (comma separated):',(old.keys||[]).join(', '));if(keys===null)return;const content=prompt('Lore content:',old.content||'');if(content===null)return;const priority=Number(prompt('Priority (higher activates first):',old.priority||0));const e={id:old.id||uid(),name,keys:keys.split(',').map(x=>x.trim()).filter(Boolean),content,priority:Number.isFinite(priority)?priority:0,enabled:old.enabled!==false};if(index>=0)c.lorebook[index]=e;else c.lorebook.push(e);saveC(c).then(done)}
const baseRender=window.render;window.render=async()=>{await baseRender();if(state.tab==='chars')decorate()};
async function decorate(){document.querySelectorAll('[data-full-card]').forEach(x=>x.remove());const cs=await get('characters')||[];document.querySelectorAll('.stack > .card').forEach((card,i)=>{const c=cs[i];if(!c)return;const row=card.querySelector('.row.wrap');if(!row)return;if(!row.querySelector('[data-card-edit]')){const b=document.createElement('button');b.className='btn';b.dataset.cardEdit=c.id;b.textContent='Card + Lore';row.appendChild(b);b.onclick=async()=>{openId=c.id;state.tab='create';await render();const main=document.querySelector('main');const existing=document.getElementById('fullCardEditor');if(existing)existing.remove();main?.appendChild(editor(await getC(c.id)))}}if(!row.querySelector('[data-card-export]')){const b=document.createElement('button');b.className='btn';b.dataset.cardExport=c.id;b.textContent='Export';row.appendChild(b);b.onclick=async()=>exportCard(await getC(c.id))}})}
const oldCreate=window.render;window.addEventListener('load',wrapPromptHook);})();
