(()=>{
let busy=false;
async function all(){return await get('conversations')||[]}
async function active(){const a=await all();return {a,x:a.find(v=>v.id===state.nfConversationId)||a.find(v=>v.characterId===state.chat)}}
function label(x,i){return x.branchName||(x.parentConversationId?`Branch ${i+1}`:'Main')}
window.nfBranchAt=async index=>{const q=await active();if(!q.x||!q.x.messages?.[index])return;const clone=JSON.parse(JSON.stringify(q.x));clone.id=crypto.randomUUID();clone.parentConversationId=q.x.id;clone.branchPoint=index;clone.branchName=`Branch · ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`;clone.createdAt=new Date().toISOString();clone.updatedAt=new Date().toISOString();clone.messages=(q.x.messages||[]).slice(0,index+1);q.a.unshift(clone);await put('conversations',q.a);state.nfConversationId=clone.id;await window.render()}
window.nfSwitchConversation=async id=>{const a=await all(),x=a.find(v=>v.id===id);if(!x)return;state.nfConversationId=id;state.chat=x.characterId;state.tab='chat';await window.render()}
async function rename(id){const a=await all(),x=a.find(v=>v.id===id);if(!x)return;const n=prompt('Rename conversation',x.branchName||'Main');if(n===null||!n.trim())return;x.branchName=n.trim();x.updatedAt=new Date().toISOString();await put('conversations',a);await window.render()}
async function addUI(){if(state.tab!=='chat'||!state.chat||busy)return;busy=true;try{const q=await active();if(!q.x)return;state.nfConversationId=q.x.id;const branches=q.a.filter(v=>v.characterId===state.chat);const head=document.querySelector('.chathead');if(head){document.querySelector('#nfBranchBar')?.remove();const bar=document.createElement('div');bar.id='nfBranchBar';bar.className='nf-branchbar';const title=document.createElement('span');title.className='nf-branchtitle';title.textContent='CONVERSATION';bar.append(title);const current=document.createElement('button');current.className='nf-branchselect';current.textContent=label(q.x,branches.indexOf(q.x));current.onclick=()=>{const list=branches.map((b,i)=>`${i+1}. ${label(b,i)}`).join('\n');const pick=prompt(`Choose a conversation:\n${list}`,String(Math.max(1,branches.indexOf(q.x)+1)));const n=Number(pick)-1;if(Number.isInteger(n)&&branches[n])window.nfSwitchConversation(branches[n].id)};bar.append(current);const rn=document.createElement('button');rn.className='nf-branchbtn';rn.textContent='✎';rn.title='Rename';rn.onclick=()=>rename(q.x.id);bar.append(rn);if(q.x.parentConversationId){const back=branches.find(v=>v.id===q.x.parentConversationId);if(back){const b=document.createElement('button');b.className='nf-branchbtn';b.textContent='↩';b.title='Return to parent';b.onclick=()=>window.nfSwitchConversation(back.id);bar.append(b)}}head.insertAdjacentElement('afterend',bar)}
 document.querySelectorAll('.messages .bubble').forEach((b,i)=>{if(b.dataset.nfRewind)return;b.dataset.nfRewind='1';const meta=b.querySelector('.bubblemeta');if(!meta)return;const btn=document.createElement('button');btn.className='mini nf-start-branch';btn.textContent='↶ Start here';btn.title='Start a new conversation branch from this message';btn.onclick=e=>{e.stopPropagation();window.nfBranchAt(i)};meta.append(' ',btn)})
}catch(e){console.warn('Nightshade rewind UI',e)}finally{busy=false}}
const oldRender=window.render;window.render=async()=>{await oldRender();await addUI()};window.addEventListener('load',()=>setTimeout(addUI,0));
})();
