(()=>{
let running=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const ago=ts=>{if(!ts)return '';const d=Date.now()-new Date(ts).getTime(),m=Math.max(0,Math.floor(d/60000));if(m<1)return 'now';if(m<60)return `${m}m`;const h=Math.floor(m/60);if(h<24)return `${h}h`;const days=Math.floor(h/24);return days<7?`${days}d`:new Date(ts).toLocaleDateString([], {month:'short',day:'numeric'})};
async function openChat(id){const all=await get('conversations')||[],i=all.findIndex(x=>x.id===id);if(i<0)return;const [x]=all.splice(i,1);all.unshift(x);await put('conversations',all);state.chat=x.characterId;state.tab='chat';state.nfConversationId=x.id;await render()}
async function removeChat(id){const all=await get('conversations')||[],x=all.find(v=>v.id===id);if(!x)return;if(!confirm('Delete this conversation?'))return;await put('conversations',all.filter(v=>v.id!==id));if(state.nfConversationId===id)state.nfConversationId=null;await render()}
async function renderChats(){const cs=await get('characters')||[],all=await get('conversations')||[];const rows=all.map((x,idx)=>{const c=cs.find(v=>v.id===x.characterId);if(!c)return '';const msgs=x.messages||[],last=msgs[msgs.length-1],preview=last?.text||c.greeting||'No messages yet';const title=x.branchName||c.name||'Unnamed';const branch=x.parentConversationId;return `<article class="nf-chatcard" data-chat-open="${esc(x.id)}"><div class="nf-chat-avatar">${c.avatar&&String(c.avatar).startsWith('data:')?`<img src="${c.avatar}" alt="">`:esc(c.avatar||c.name?.[0]||'?')}</div><div class="nf-chatbody"><div class="nf-chattop"><strong>${esc(title)}</strong><span>${esc(ago(x.updatedAt||x.createdAt||last?.at))}</span></div><div class="nf-charchar">${esc(c.name)}${branch?' · branch':''}</div><div class="nf-chatpreview">${esc(preview)}</div></div><button class="nf-chatmore" data-chat-delete="${esc(x.id)}" title="Delete conversation">⋯</button></article>`}).filter(Boolean).join('');
return `<main class="shell nf-chats-page"><div class="hero"><div class="brand">NIGHTSHADE FORGE</div><div class="nf-home-title"><div><h1>Chats</h1><p class="muted">Your conversations stay in this browser.</p></div><button class="iconbtn nf-newchat" data-tab="chars">＋</button></div></div><section class="card nf-chatlist-card"><div class="nf-chatsearch"><span>⌕</span><input id="nfChatSearch" class="input" placeholder="Search conversations…"></div><div id="nfChatList" class="nf-chatlist">${rows||'<div class="nf-emptychat"><div>◌</div><strong>No conversations yet</strong><span>Create a character and start a chat.</span></div>'}</div></section>${nav()}</main>`}
async function decorateHome(){if(state.tab!=='home'||running)return;running=true;try{const root=document.querySelector('#app');if(!root)return;root.innerHTML=await renderChats();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.chat=null;render()});document.querySelectorAll('[data-chat-open]').forEach(b=>b.onclick=()=>openChat(b.dataset.chatOpen));document.querySelectorAll('[data-chat-delete]').forEach(b=>b.onclick=e=>{e.stopPropagation();removeChat(b.dataset.chatDelete)});const search=document.querySelector('#nfChatSearch');if(search)search.oninput=()=>{const q=search.value.toLowerCase();document.querySelectorAll('.nf-chatcard').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?'':'none')};}catch(e){console.warn('Nightshade chat list',e)}finally{running=false}}
const oldRender=window.render;window.render=async()=>{await oldRender();await decorateHome()};window.addEventListener('load',()=>setTimeout(decorateHome,0));
})();
