(()=>{
if(window.__nfChatterboxVoice)return;window.__nfChatterboxVoice=1;
const MODEL='ttslab/chatterbox-turbo-webgpu';
let engine=null,loading=null;
const STYLES=[
 ['natural','Natural','Clean expressive delivery'],
 ['dark','Dark','Low, dramatic delivery'],
 ['warm','Warm','Soft intimate delivery'],
 ['cinematic','Cinematic','Dramatic narration'],
 ['playful','Playful','Lighter playful delivery']
];
function wavBlob(audio,sr){const data=audio instanceof Float32Array?audio:Float32Array.from(audio||[]);const ab=new ArrayBuffer(44+data.length*2),dv=new DataView(ab);const w=(o,s)=>{for(let i=0;i<s.length;i++)dv.setUint8(o+i,s.charCodeAt(i))};w(0,'RIFF');dv.setUint32(4,36+data.length*2,true);w(8,'WAVE');w(12,'fmt ');dv.setUint32(16,16,true);dv.setUint16(20,1,true);dv.setUint16(22,1,true);dv.setUint32(24,sr,true);dv.setUint32(28,sr*2,true);dv.setUint16(32,2,true);dv.setUint16(34,16,true);w(36,'data');dv.setUint32(40,data.length*2,true);for(let i=0;i<data.length;i++){const x=Math.max(-1,Math.min(1,data[i]));dv.setInt16(44+i*2,x<0?x*0x8000:x*0x7fff,true)}return new Blob([ab],{type:'audio/wav'})}
async function load(){if(engine)return engine;if(loading)return loading;loading=(async()=>{const mod=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.2/+esm');const pipeline=mod.pipeline||mod.default?.pipeline;if(!pipeline)throw Error('Transformers.js did not load');if(!('gpu'in navigator&&navigator.gpu))throw Error('Chatterbox requires WebGPU on this device');engine=await pipeline('text-to-speech',MODEL,{device:'webgpu',dtype:'q4f16'});return engine})().finally(()=>{loading=null});return loading}
async function speak(text,style='natural'){const raw=String(text||'').trim();if(!raw)return false;try{const pipe=await load();const tag=style==='dark'?'[sigh] ':style==='warm'?'[whisper] ':style==='playful'?'[chuckle] ':style==='cinematic'?'[dramatic] ':'';const out=await pipe(tag+raw);const audio=out?.audio||out?.[0]?.audio||out?.[0];const sr=out?.sampling_rate||out?.[0]?.sampling_rate||24000;if(!audio)throw Error('No audio returned');const url=URL.createObjectURL(wavBlob(audio,sr));const a=new Audio(url);a.onended=()=>URL.revokeObjectURL(url);await a.play();return true}catch(e){console.warn('Chatterbox local TTS failed',e);return false}}
async function assign(charId,style){const cs=await get('characters')||[],c=cs.find(x=>x.id===charId);if(!c)return;c.voice={...(c.voice||{}),provider:'chatterbox',providerVoiceId:style,providerVoiceName:'Chatterbox · '+(STYLES.find(x=>x[0]===style)?.[1]||style),savedVoiceId:null,browserVoice:null,browserVoiceName:null,autoRead:true};await put('characters',cs);return c}
function open(charId){const ov=document.createElement('div');ov.className='nf-voice-modal';ov.innerHTML='<section class="nf-voice-sheet"><div class="row"><div class="grow"><div class="brand">CHATTERBOX · FREE LOCAL AI</div><h2 style="margin:2px 0">Expressive local voice</h2><div class="muted tiny">Runs on-device with WebGPU. No API key or subscription. First use downloads roughly 539 MB of model data.</div></div><button class="iconbtn" data-x>×</button></div><div id="nfCBRows" class="stack" style="margin-top:10px"></div><div id="nfCBStatus" class="nf-voice-help">Pick a delivery style and preview it.</div></section>';document.body.append(ov);const rows=ov.querySelector('#nfCBRows'),status=ov.querySelector('#nfCBStatus');rows.innerHTML=STYLES.map(v=>`<div class="nf-voice-row"><button class="nf-voice-play" data-preview="${v[0]}">▶</button><div class="nf-voice-name"><strong>${v[1]}</strong><span>${v[2]}</span></div><button class="btn" data-use="${v[0]}">Use</button></div>`).join('');rows.querySelectorAll('[data-preview]').forEach(b=>b.onclick=async()=>{status.textContent='Loading Chatterbox / generating preview...';const ok=await speak('This is an expressive local Chatterbox voice preview.',b.dataset.preview);status.textContent=ok?'Preview finished.':'Chatterbox needs WebGPU and enough device memory.'});rows.querySelectorAll('[data-use]').forEach(b=>b.onclick=async()=>{await assign(charId,b.dataset.use);ov.remove();await render()});ov.querySelector('[data-x]').onclick=()=>ov.remove();ov.addEventListener('click',e=>e.target===ov&&ov.remove())}
window.nfChatterbox={speak,load,open,assign,styles:STYLES};
})();
