(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const baseRender=window.render;
let audio=null, audioUrl=null, videoUrl=null, mediaRecorder=null, chunks=[], raf=0, streamMode='spectrum', analyser=null, audioCtx=null, sourceNode=null, activeProject=null;
const modes=['spectrum','pulse','orbit','lyrics','nebula'];
function dbGet(k){return get(k)} function dbPut(k,v){return put(k,v)}
function studio(){return `<main class="shell studio"><header class="topbar"><div><div class="brand">NIGHTSHADE MEDIA LAB</div><h1>Mini DJ + Visualizer</h1><div class="muted">Local-first music video forge</div></div><button class="iconbtn" data-tab="home">×</button></header>
<section class="card stack"><div class="row wrap"><label class="btn filebtn">＋ Add media<input id="mediaFiles" type="file" accept="audio/*,video/*,image/*" multiple hidden></label><button class="btn" id="newProject">＋ New project</button><button class="btn" id="saveProject">Save project</button></div><div id="mediaList" class="media-list"></div></section>
<section class="card stack"><div class="visual-wrap"><canvas id="visualCanvas"></canvas><div id="visualText" class="visual-text"></div></div><div class="row wrap"><button class="round primary" id="playBtn">▶</button><button class="btn" id="muteOriginal">Mute original</button><button class="btn" id="recordBtn">● Record visual</button><button class="btn" id="downloadBtn" disabled>⇩ Download video</button></div><div class="timeline"><input id="seek" type="range" min="0" max="100" value="0"><span id="timeLabel">0:00 / 0:00</span></div></section>
<section class="card stack"><h2>Visual direction</h2><label>Prompt <textarea id="visualPrompt" class="input" rows="3" placeholder="Optional: describe the visual story, colors, characters, camera movement, transitions, lyrics..."></textarea></label><div class="row wrap"><label class="btn">Mode <select id="visualMode" class="select">${modes.map(m=>`<option value="${m}">${m}</option>`).join('')}</select></label><button class="btn primary" id="applyPrompt">Generate visual stream</button><button class="btn" id="makeVariants">Generate multiple variants</button></div><p class="muted tiny">Default mode analyzes the audio and creates procedural beat-reactive visuals. Prompt mode uses your text as visual direction. External AI video providers can be connected later through adapters.</p></section>
<section class="card stack"><h2>Audio + media mixer</h2><label class="switchrow"><input id="originalMute" type="checkbox"> Mute original media audio</label><label class="btn filebtn">＋ Add soundtrack<input id="trackFile" type="file" accept="audio/*" hidden></label><div id="trackName" class="muted">No replacement soundtrack loaded.</div><label>Track volume <input id="trackVol" type="range" min="0" max="1" step="0.01" value="1"></label><label>Original volume <input id="origVol" type="range" min="0" max="1" step="0.01" value="1"></label></section>
<section class="card stack"><h2>Lyrics / message</h2><textarea id="lyrics" class="input" rows="5" placeholder="Paste lyrics or a message. The visualizer can reveal lines during playback."></textarea><label class="switchrow"><input id="showLyrics" type="checkbox" checked> Show lyrics on stream</label></section>
<section class="card stack"><h2>Projects + activity</h2><div id="projects"></div><div id="activity" class="activity"></div></section>${nav()}</main>`}
function canvasSetup(){const c=document.querySelector('#visualCanvas');if(!c)return;const resize=()=>{const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;};resize();addEventListener('resize',resize,{passive:true});return c}
function logActivity(text){dbGet('mediaActivity').then(a=>{a=a||[];a.unshift({text,at:new Date().toISOString()});return dbPut('mediaActivity',a.slice(0,100))}).then(renderActivity)}
async function renderActivity(){const el=document.querySelector('#activity');if(!el)return;const a=await dbGet('mediaActivity')||[];el.innerHTML=a.slice(0,12).map(x=>`<div class="activity-row"><span>${esc(x.text)}</span><small>${new Date(x.at).toLocaleString()}</small></div>`).join('')||'<div class="muted">No activity yet.</div>'}
async function renderProjects(){const el=document.querySelector('#projects');if(!el)return;const ps=await dbGet('mediaProjects')||[];el.innerHTML=ps.map(p=>`<div class="project-row"><div><strong>${esc(p.name)}</strong><div class="tiny muted">${p.files?.length||0} media · ${new Date(p.updatedAt).toLocaleString()}</div></div><button class="btn" data-load-project="${p.id}">Load</button></div>`).join('')||'<div class="muted">No saved media projects.</div>'}
function ensureAudio(){if(audio)return;audio=document.createElement('audio');audio.preload='auto';audio.crossOrigin='anonymous';audio.style.display='none';document.body.appendChild(audio)}
async function loadFile(file){ensureAudio();if(file.type.startsWith('audio/')){if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=URL.createObjectURL(file);audio.src=audioUrl;audio.load();activeProject=activeProject||{id:crypto.randomUUID(),name:file.name.replace(/\.[^.]+$/,''),files:[]};activeProject.files.push({name:file.name,type:file.type,size:file.size});renderMediaList();logActivity('Loaded audio: '+file.name)}else if(file.type.startsWith('video/')){const v=document.createElement('video');v.src=URL.createObjectURL(file);v.muted=true;v.loop=true;v.playsInline=true;v.className='source-video';document.querySelector('.visual-wrap').appendChild(v);v.play().catch(()=>{});activeProject=activeProject||{id:crypto.randomUUID(),name:file.name,files:[]};activeProject.files.push({name:file.name,type:file.type,size:file.size});renderMediaList();logActivity('Loaded video: '+file.name)}else{activeProject=activeProject||{id:crypto.randomUUID(),name:file.name,files:[]};activeProject.files.push({name:file.name,type:file.type,size:file.size});renderMediaList();logActivity('Loaded image: '+file.name)}}
function renderMediaList(){const el=document.querySelector('#mediaList');if(!el)return;el.innerHTML=(activeProject?.files||[]).map((f,i)=>`<div class="media-row"><span>${esc(f.name)}</span><small>${esc(f.type)}</small><button class="mini" data-remove-media="${i}">×</button></div>`).join('')||'<div class="muted">Add MP3, WAV, MP4, WebM, images, or other browser-supported media.</div>'}
function initAnalyser(){if(!audio||analyser)return;try{audioCtx=new (AudioContext||webkitAudioContext)();sourceNode=audioCtx.createMediaElementSource(audio);analyser=audioCtx.createAnalyser();analyser.fftSize=256;sourceNode.connect(analyser);analyser.connect(audioCtx.destination)}catch(e){console.warn(e)}}
function draw(){const c=document.querySelector('#visualCanvas');if(!c)return;const ctx=c.getContext('2d'),w=c.width,h=c.height;let data=analyser?new Uint8Array(analyser.frequencyBinCount):null;const prompt=document.querySelector('#visualPrompt')?.value||'';const lyric=document.querySelector('#lyrics')?.value||'';function frame(t){ctx.clearRect(0,0,w,h);let energy=0;if(data){analyser.getByteFrequencyData(data);for(const x of data)energy+=x;energy/=data.length/255}else energy=100+45*Math.sin(t/500);const beat=Math.max(0,energy/255);ctx.save();ctx.translate(w/2,h/2);const max=Math.min(w,h)*.42;
if(streamMode==='spectrum'||streamMode==='nebula'){for(let i=0;i<64;i++){const v=data?data[i%data.length]/255:0.25+0.2*Math.sin(t/300+i);const a=i*Math.PI*2/64;const r=80+v*max;ctx.beginPath();ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r);ctx.lineTo(Math.cos(a)*(r+30+v*80),Math.sin(a)*(r+30+v*80));ctx.strokeStyle=`hsla(${(i*8+t/18)%360},90%,65%,${.35+v*.65})`;ctx.lineWidth=2+v*4;ctx.stroke()}}
else if(streamMode==='pulse'){const r=80+beat*max*.65;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.strokeStyle=`hsla(${(t/12)%360},90%,65%,.8)`;ctx.lineWidth=8+beat*20;ctx.stroke();for(let i=0;i<5;i++){ctx.beginPath();ctx.arc(0,0,r+i*30+beat*20,0,Math.PI*2);ctx.strokeStyle=`hsla(${(t/10+i*50)%360},90%,65%,${.2-i*.025})`;ctx.stroke()}}
else if(streamMode==='orbit'){for(let i=0;i<10;i++){const a=t/1000*(i%2?-1:1)+i*.63,r=70+i*22+beat*40;ctx.beginPath();ctx.arc(Math.cos(a)*r,Math.sin(a)*r,8+beat*18,0,Math.PI*2);ctx.fillStyle=`hsla(${(i*35+t/20)%360},90%,65%,.8)`;ctx.fill()}}
else{for(let i=0;i<18;i++){const a=t/700+i*.9,r=60+i*15+beat*70;ctx.beginPath();ctx.arc(Math.cos(a)*r,Math.sin(a)*r,12+beat*14,0,Math.PI*2);ctx.fillStyle=`hsla(${(i*20+t/15)%360},90%,60%,.35)`;ctx.fill()}}
ctx.restore();const show=document.querySelector('#showLyrics')?.checked;const vt=document.querySelector('#visualText');if(vt){if(show&&lyric){const lines=lyric.split(/\n+/).filter(Boolean);const idx=Math.floor((audio?.currentTime||0)/Math.max(1,(audio?.duration||60)/Math.max(1,lines.length)));vt.textContent=lines[Math.min(idx,lines.length-1)]||''}else if(prompt)vt.textContent=prompt;else vt.textContent='NIGHTSHADE MEDIA LAB'}}raf=requestAnimationFrame(frame)}cancelAnimationFrame(raf);frame(0)}
function formatTime(x){if(!isFinite(x))return'0:00';return `${Math.floor(x/60)}:${String(Math.floor(x%60)).padStart(2,'0')}`}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});canvasSetup();ensureAudio();draw();
const mf=document.querySelector('#mediaFiles');mf.onchange=async()=>{for(const f of mf.files)await loadFile(f);mf.value=''};
const play=document.querySelector('#playBtn');play.onclick=async()=>{if(!audio.src){alert('Add an audio file first.');return}initAnalyser();if(audioCtx?.state==='suspended')await audioCtx.resume();if(audio.paused){await audio.play();play.textContent='Ⅱ';logActivity('Playback started')}else{audio.pause();play.textContent='▶';logActivity('Playback paused')}};
audio.ontimeupdate=()=>{const s=document.querySelector('#seek');if(s){s.value=audio.duration?audio.currentTime/audio.duration*100:0;document.querySelector('#timeLabel').textContent=`${formatTime(audio.currentTime)} / ${formatTime(audio.duration)}`}};
document.querySelector('#seek').oninput=e=>{if(audio.duration)audio.currentTime=+e.target.value/100*audio.duration};
const mute=document.querySelector('#originalMute');mute.onchange=e=>{audio.muted=e.target.checked;document.querySelector('#muteOriginal').textContent=e.target.checked?'Unmute original':'Mute original'};document.querySelector('#muteOriginal').onclick=()=>{audio.muted=!audio.muted;mute.checked=audio.muted;document.querySelector('#muteOriginal').textContent=audio.muted?'Unmute original':'Mute original'};
document.querySelector('#trackVol').oninput=e=>{trackVolume=+e.target.value};document.querySelector('#origVol').oninput=e=>audio.volume=+e.target.value;document.querySelector('#visualMode').onchange=e=>{streamMode=e.target.value;draw()};document.querySelector('#applyPrompt').onclick=()=>{streamMode=document.querySelector('#visualMode').value;draw();logActivity('Generated visual stream: '+streamMode)};
document.querySelector('#makeVariants').onclick=()=>{const old=streamMode;const variants=modes.map(m=>({id:crypto.randomUUID(),mode:m,prompt:document.querySelector('#visualPrompt').value,createdAt:new Date().toISOString()}));dbPut('mediaVariants',variants);alert('Created '+variants.length+' visual variants. Pick a mode and record/download each one.');logActivity('Generated '+variants.length+' visual variants');streamMode=old};
document.querySelector('#trackFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;trackUrl=URL.createObjectURL(f);trackName=f.name;document.querySelector('#trackName').textContent='Replacement track: '+f.name;logActivity('Loaded replacement soundtrack: '+f.name)};
document.querySelector('#saveProject').onclick=async()=>{if(!activeProject){alert('Add media first.');return}activeProject.updatedAt=new Date().toISOString();activeProject.prompt=document.querySelector('#visualPrompt').value;activeProject.mode=streamMode;activeProject.lyrics=document.querySelector('#lyrics').value;const ps=await dbGet('mediaProjects')||[];const i=ps.findIndex(p=>p.id===activeProject.id);if(i>=0)ps[i]=activeProject;else ps.unshift(activeProject);await dbPut('mediaProjects',ps);await renderProjects();logActivity('Saved project: '+activeProject.name)};
document.querySelector('#newProject').onclick=()=>{activeProject=null;renderMediaList();logActivity('Started new media project')};
document.querySelectorAll('[data-remove-media]').forEach(b=>b.onclick=()=>{activeProject.files.splice(+b.dataset.removeMedia,1);renderMediaList()});
document.querySelectorAll('[data-load-project]').forEach(b=>b.onclick=async()=>{const ps=await dbGet('mediaProjects')||[],p=ps.find(x=>x.id===b.dataset.loadProject);if(p){activeProject=p;document.querySelector('#visualPrompt').value=p.prompt||'';document.querySelector('#lyrics').value=p.lyrics||'';streamMode=p.mode||'spectrum';document.querySelector('#visualMode').value=streamMode;renderMediaList();draw();logActivity('Loaded project: '+p.name)}});
document.querySelector('#recordBtn').onclick=startRecording;document.querySelector('#downloadBtn').onclick=downloadRecording;document.querySelector('#lyrics').oninput=draw;document.querySelector('#showLyrics').onchange=draw;renderProjects();renderActivity()}
let trackUrl='',trackName='',trackVolume=1;
function startRecording(){const c=document.querySelector('#visualCanvas');if(!c.captureStream){alert('This browser does not support canvas recording.');return}chunks=[];const vs=c.captureStream(30);mediaRecorder=new MediaRecorder(vs,{mimeType:'video/webm'});mediaRecorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};mediaRecorder.onstop=()=>{videoUrl=URL.createObjectURL(new Blob(chunks,{type:'video/webm'}));document.querySelector('#downloadBtn').disabled=false;logActivity('Recorded live visualization')};mediaRecorder.start();document.querySelector('#recordBtn').textContent='■ Stop recording';document.querySelector('#recordBtn').onclick=()=>{mediaRecorder.stop();document.querySelector('#recordBtn').textContent='● Record visual';document.querySelector('#recordBtn').onclick=startRecording};logActivity('Started visual recording')}
function downloadRecording(){if(!videoUrl)return;const a=document.createElement('a');a.href=videoUrl;a.download=(activeProject?.name||'nightshade-visual')+'.webm';a.click();logActivity('Downloaded visualization video')}
window.render=async()=>{if(state.tab==='studio'){document.querySelector('#app').innerHTML=studio();bind();return}await baseRender();if(sessionStorage.getItem('nf_unlocked')==='1'&&!state.locked){const n=document.querySelector('.nav');if(n&&!n.querySelector('[data-tab="studio"]')){const b=document.createElement('button');b.dataset.tab='studio';b.innerHTML='◉<br><small>Media DJ</small>';n.appendChild(b);b.onclick=()=>{state.tab='studio';render()}}}};
})();