(()=>{
let menu=null,longTimer=null;
function close(){menu?.remove();menu=null}
function make(i){close();const b=document.createElement('div');b.className='nf-msgmenu';b.innerHTML=`<button data-a="edit">✎ Edit</button><button data-a="delete">⌫ Delete</button><button data-a="regen">↻ Regenerate</button><button data-a="branch">⑂ Start branch</button><button data-a="copy">▣ Copy</button><button data-a="speak">◖ Speak</button>`;document.body.append(b);menu=b;const bubble=document.querySelectorAll('.messages .bubble')[i];const r=bubble?.getBoundingClientRect();if(r){b.style.left=Math.min(Math.max(8,r.left),innerWidth-190)+'px';b.style.top=Math.min(r.bottom+6,innerHeight-310)+'px'}b.querySelectorAll('button').forEach(x=>x.onclick=()=>action(x.dataset.a,i))}
async function active(){const a=await get('conversations')||[];return {a,x:a.find(v=>v.id===state.nfConversationId)||a.find(v=>v.characterId===state.chat)}}
async function action(a,i){const q=await active(),m=q.x?.messages?.[i];close();if(!m)return;if(a==='copy'){await navigator.clipboard?.writeText(m.text||'');return}if(a==='speak'){if(window.speakText)window.speakText(m.text||'');else speechSynthesis?.speak(new SpeechSynthesisUtterance(m.text||''));return}if(a==='branch'){window.nfBranchAt?.(i);return}if(a==='regen'){document.querySelector(`.messages .bubble:nth-of-type(${i+1}) [data-regenerate]`)?.click();document.querySelectorAll('[data-regenerate]')[i]?.click();return}if(a==='edit'){const t=prompt('Edit message',m.text||'');if(t===null||!t.trim())return;m.text=t.trim();m.edited=true;m.editedAt=new Date().toISOString();await put('conversations',q.a);await render();return}if(a==='delete'){if(!confirm('Delete this message?'))return;q.x.messages.splice(i,1);q.x.updatedAt=new Date().toISOString();await put('conversations',q.a);await render()}}
function bind(){document.querySelectorAll('.messages .bubble').forEach((b,i)=>{if(b.dataset.nfMenu)return;b.dataset.nfMenu='1';b.addEventListener('contextmenu',e=>{e.preventDefault();make(i)});b.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')longTimer=setTimeout(()=>make(i),550)});['pointerup','pointercancel','pointerleave'].forEach(t=>b.addEventListener(t,()=>clearTimeout(longTimer)));});}
const style=document.createElement('style');style.textContent='.nf-msgmenu{position:fixed;z-index:9999;width:180px;padding:5px;border:1px solid #4a3150;border-radius:14px;background:#120d15;box-shadow:0 16px 40px #0009;display:grid;gap:2px}.nf-msgmenu button{min-height:40px;border:0;border-radius:9px;background:transparent;color:#eee;text-align:left;padding:8px 10px;font-size:12px}.nf-msgmenu button:hover{background:#281a2c;color:#ff72c2}.nf-msgmenu button:active{background:#38213b}';document.head.append(style);document.addEventListener('pointerdown',e=>{if(menu&&!menu.contains(e.target))close()});const oldRender=window.render;window.render=async()=>{await oldRender();bind()};window.addEventListener('load',()=>setTimeout(bind,0));
})();
