(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const voices=()=>speechSynthesis?.getVoices?.()||[];
let callTimer=null,callOn=false,rec=null,chunks=[];
async function currentChar(){if(typeof state==='undefined'||!state.chat)return null;return (await get('characters')||[]).find(c=>c.id===state.chat)}
async function saveChar(c){const cs=await get('characters')||[],i=cs.findIndex(x=>x.id===c.id);if(i>=0)cs[i]=c;await put('characters',cs)}
function voiceOptions(selected){return voices().map((v,i)=>`<option value="${i}" ${v.name===selected?'selected':''}>${esc(v.name)} — ${esc(v.lang)}</option>`).join('')}
function speak(text,c){if(!('speechSynthesis'in window))return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const v=voices().find(x=>x.name===c?.voice?.browserVoice);if(v)u.voice=v;u.rate=Number(c?.voice?.rate)||1;u.pitch=Number(c?.voice?.pitch)||1;speechSynthesis.speak(u)}
function voicePanel(c){c.voice=c.voice||{};return `<section class="card stack" id="characterVoicePanel"><h2>Character Voice</h2><p class="muted">Choose a browser voice for this character. The setting is saved with the character.</p><label>Voice<select id="charVoice" class="input"><option value="">Browser default</option>${voiceOptions(c.voice.browserVoice||'')}</select></label><div class="row wrap"><label>Rate<input id="charRate" class="input" type="number" min="0.5" max="2" step="0.05" value="${c.voice.rate||1}"></label><label>Pitch<input id="charPitch" class="input" type="number" min="0" max="2" step="0.05" value="${c.voice.pitch||1}"></label></div><div class="row wrap"><button class="btn" id="saveCharVoice">Save voice</button><button class="btn" id="testCharVoice">▶ Test</button></div><p class="tiny muted">For true custom AI voices, connect a TTS provider later; this mode uses the device/browser voice engine and requires no API key.</p></section>`}
function callUI(c){return `<main class="shell"><header class="topbar"><div><div class="brand">NIGHTSHADE CALL</div><h1>${esc(c.name)}</h1></div><button class="iconbtn" id="closeCall">×</button></header><section class="card callcard"><div class="avatar large">${esc(c.avatar||c.name?.[0]||'?')}</div><h2>${esc(c.name)}</h2><div id="callState" class="muted">Ready</div><div id="callTime" class="tiny">00:00</div><div class="call-controls"><button class="round primary" id="callToggle">☎</button><button class="round" id="callMute">🎙</button><button class="round" id="callStop">■</button></div><div id="callTranscript" class="call-transcript"></div><p class="tiny muted">Call mode uses browser speech recognition when available. Your transcript is saved to this conversation.</p></section></main>`}
async function startCall(c){if(callOn)return;callOn=true;const st=$('#callState'),toggle=$('#callToggle');st.textContent='Listening…';toggle.textContent='⏹';const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){st.textContent='Speech recognition unavailable on this device';return}rec=new SR();rec.continuous=true;rec.interimResults=false;rec.lang=navigator.language||'en-US';rec.onresult=async e=>{const text=[...e.results].slice(-1).map(r=>r[0].transcript).join(' ').trim();if(!text)return;$('#callTranscript').insertAdjacentHTML('beforeend',`<div><b>You:</b> ${esc(text)}</div>`);const all=await get('conversations')||[],x=all.find(v=>v.characterId===c.id);if(!x)return;x.messages.push({role:'user',text,status:'sent',call:true});await put('conversations',all);try{const answer=await window.nfCallReply(c,x);if(answer){x.messages.push({role:'assistant',text:answer,status:'received',call:true});await put('conversations',all);$('#callTranscript').insertAdjacentHTML('beforeend',`<div><b>${esc(c.name)}:</b> ${esc(answer)}</div>`);speak(answer,c)}}catch(err){$('#callTranscript').insertAdjacentHTML('beforeend',`<div class="muted">⚠ ${esc(err.message)}</div>`)}};rec.onerror=e=>{st.textContent='Mic error: '+e.error};rec.onend=()=>{if(callOn)try{rec.start()}catch{}};try{rec.start()}catch(e){st.textContent=e.message}let sec=0;clearInterval(callTimer);callTimer=setInterval(()=>{sec++;const m=String(Math.floor(sec/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');$('#callTime').textContent=m+':'+s},1000)}
function stopCall(){callOn=false;try{rec?.stop()}catch{}rec=null;clearInterval(callTimer);speechSynthesis?.cancel();$('#callState')?.replaceChildren(document.createTextNode('Call ended'));$('#callToggle')?.replaceChildren(document.createTextNode('☎'))}
window.nfCallReply=async(c,x)=>{const p=await get('provider');if(!p?.base||!p?.key)throw new Error('Connect a provider in Provider Studio first.');const model=x.model||p.model;if(!model)throw new Error('Choose a chat model first.');const history=x.messages.slice(-30).map(m=>({role:m.role,content:m.text}));const system=typeof buildSystem==='function'?buildSystem(c,x,p,false):`Roleplay as ${c.name}. Character fidelity and continuity are priorities.`;const r=await fetch(p.base,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+p.key},body:JSON.stringify({model,messages:[{role:'system',content:system},...history],temperature:.9,max_tokens:1000})});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Provider error');return j.choices?.[0]?.message?.content?.trim()||''}
const baseRender=window.render;window.render=async()=>{await baseRender();if(state.tab==='voices')decorateVoicePage()};
async function decorateVoicePage(){document.querySelectorAll('[data-voice-char]').forEach(x=>x.remove());const cs=await get('characters')||[];const main=document.querySelector('main');if(!main||!cs.length)return;const box=document.createElement('section');box.className='card stack';box.dataset.voiceChar='1';box.innerHTML='<h2>Character Voices</h2><p class="muted">Assign a voice to each character.</p>'+cs.map(c=>`<div class="row"><div class="avatar">${esc(c.avatar||c.name?.[0]||'?')}</div><div class="grow"><strong>${esc(c.name)}</strong><div class="tiny muted">${esc(c.voice?.browserVoice||'Browser default')}</div></div><button class="btn" data-open-voice="${c.id}">Configure</button></div>`).join('');main.insertBefore(box,main.lastElementChild);box.querySelectorAll('[data-open-voice]').forEach(b=>b.onclick=async()=>{const c=await currentCharById(b.dataset.openVoice);const p=document.getElementById('characterVoicePanel');p?.remove();main.insertBefore(voicePanel(c),box);bindVoice(c)})}
async function currentCharById(id){return (await get('characters')||[]).find(c=>c.id===id)}
function bindVoice(c){$('#saveCharVoice').onclick=async()=>{c.voice={browserVoice:$('#charVoice').selectedOptions[0]?.textContent?.split(' — ')[0]||'',rate:Number($('#charRate').value)||1,pitch:Number($('#charPitch').value)||1};await saveChar(c);alert('Character voice saved locally.')};$('#testCharVoice').onclick=()=>speak(`Hello. I am ${c.name}.`,c)}
window.addEventListener('load',()=>speechSynthesis?.addEventListener?.('voiceschanged',()=>{if(state.tab==='voices')render()}));
const oldBind=window.bindForge;window.bindForge=function(){if(oldBind)oldBind();document.querySelectorAll('[data-call]').forEach(b=>b.onclick=async()=>{const c=await currentChar();if(!c)return;state.tab='call';await render();const main=document.querySelector('#app');main.innerHTML=callUI(c);$('#closeCall').onclick=()=>{stopCall();state.tab='voices';render()};$('#callToggle').onclick=()=>callOn?stopCall():startCall(c);$('#callStop').onclick=stopCall;$('#callMute').onclick=()=>{if(rec){try{rec.stop()}catch{}rec=null;$('#callState').textContent='Mic paused'}}})};
})();
