(()=>{
if(window.__nfWorkflow)return;window.__nfWorkflow=1;
const uid=()=>crypto.randomUUID(),now=()=>new Date().toISOString();
const characters=async()=>await get('characters')||[],conversations=async()=>await get('conversations')||[];
async function ensureConversation(c){const all=await conversations();let x=all.find(v=>v.characterId===c.id);if(!x){x={id:uid(),characterId:c.id,messages:[],memory:[],model:'',createdAt:now(),updatedAt:now()};all.unshift(x);await put('conversations',all);return x}let changed=false;if(!Array.isArray(x.messages)){x.messages=[];changed=true}if(!Array.isArray(x.memory)){x.memory=[];changed=true}if(!x.createdAt){x.createdAt=now();changed=true}if(!x.updatedAt){x.updatedAt=x.createdAt;changed=true}if(changed)await put('conversations',all);return x}
async function normalize(){const cs=await characters();let changed=false;cs.forEach(c=>{if(!c.id){c.id=uid();changed=true}if(!c.name)c.name='Unnamed';if(!Array.isArray(c.tags))c.tags=[];if(!Array.isArray(c.memory))c.memory=[];if(!c.createdAt){c.createdAt=now();changed=true}if(!c.updatedAt){c.updatedAt=c.createdAt;changed=true}});if(changed)await put('characters',cs);for(const c of cs)await ensureConversation(c)}
function startChat(id){state.chat=id;state.tab='chat';state.nfConversationId=null;render()}
async function decorateCharacters(){if(state.tab!=='chars')return;const cs=await characters();document.querySelectorAll('[data-chat]').forEach(b=>{if(b.dataset.nfWorkflowBound)return;b.dataset.nfWorkflowBound='1';b.onclick=()=>startChat(b.dataset.chat)});const cards=[...document.querySelectorAll('.stack > .card')];cards.forEach((card,i)=>{const c=cs[i],row=card.querySelector('.row.wrap');if(!c||!row||row.querySelector('[data-character-chat]'))return;const b=document.createElement('button');b.className='btn primary';b.dataset.characterChat=c.id;b.textContent='Chat';b.onclick=()=>startChat(c.id);row.insertBefore(b,row.firstChild)})}
async function bindSaveState(){const b=document.getElementById('saveForge');if(!b||b.dataset.nfWorkflowSave)return;b.dataset.nfWorkflowSave='1';b.addEventListener('click',()=>setTimeout(async()=>{const cs=await characters();const latest=cs[cs.length-1];if(latest)await ensureConversation(latest)},100))}
const oldRender=window.render;window.render=async()=>{await oldRender();try{await normalize();await decorateCharacters();await bindSaveState()}catch(e){console.warn('Nightshade workflow',e)}};
window.addEventListener('load',()=>setTimeout(async()=>{try{await normalize();await window.render()}catch(e){console.warn('Nightshade workflow init',e)}},250));
})();
