const K='nightcast-podcast-v1',AK='nightcast-api-v1';
let db=JSON.parse(localStorage.getItem(K)||'null')||{characters:[{id:'a',name:'Host',bio:'Curious interviewer',personality:'observant, quick-witted',style:'natural and conversational',catchphrase:'Let’s get into it.',voice:'',rate:.95,pitch:1},{id:'b',name:'Raven',bio:'Dry, mysterious co-host',personality:'sarcastic, intelligent, guarded',style:'slow, dry, low-key',catchphrase:'Obviously.',voice:'',rate:.9,pitch:.8}],episodes:[]};
let api=JSON.parse(localStorage.getItem(AK)||'null')||{provider:'gemini',geminiKey:'',geminiModel:'gemini-3.8-flash',openrouterKey:'',openrouterModel:'deepseek/deepseek-r1',elevenKey:'',elevenVoice:''};
let cast=db.characters.slice(0,2).map(c=>c.id),current=null;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function persist(){localStorage.setItem(K,JSON.stringify(db));renderCast();renderEpisodes()}
function saveApi(){localStorage.setItem(AK,JSON.stringify(api))}
function renderCast(){$('cast').innerHTML=cast.map(id=>{const c=db.characters.find(x=>x.id===id);return c?`<div class="castItem"><span><b>${esc(c.name)}</b><br><small>${esc(c.style||'')}</small></span><button onclick="removeCast('${id}')">×</button></div>`:''}).join('')||'<p>No cast yet.</p>'}
window.removeCast=id=>{cast=cast.filter(x=>x!==id);renderCast()};
$('addCast').onclick=()=>{const u=db.characters.find(c=>!cast.includes(c.id));if(u){cast.push(u.id);renderCast()}};
$('manageCast').onclick=()=>{$('charId').value='';$('charForm').reset();loadVoices();$('charDialog').showModal()};
function loadVoices(selected=''){const s=$('charVoice'),vs=speechSynthesis.getVoices();s.innerHTML='<option value="">Device default</option>'+vs.map(v=>`<option>${esc(v.name)}</option>`).join('');s.value=selected}
speechSynthesis.onvoiceschanged=()=>loadVoices();
$('apiBtn').onclick=()=>{ $('aiProvider').value=api.provider||'gemini';$('geminiKey').value=api.geminiKey||'';$('geminiModel').value=api.geminiModel||'gemini-3.8-flash';$('openrouterKey').value=api.openrouterKey||'';$('openrouterModel').value=api.openrouterModel||'deepseek/deepseek-r1';$('elevenKey').value=api.elevenKey||'';$('elevenVoice').value=api.elevenVoice||'';$('apiDialog').showModal()};
$('apiForm').onsubmit=e=>{e.preventDefault();api={provider:$('aiProvider').value,geminiKey:$('geminiKey').value.trim(),geminiModel:$('geminiModel').value,openrouterKey:$('openrouterKey').value.trim(),openrouterModel:$('openrouterModel').value.trim()||'deepseek/deepseek-r1',elevenKey:$('elevenKey').value.trim(),elevenVoice:$('elevenVoice').value.trim()};saveApi();$('apiDialog').close();alert('API settings saved on this device.')};
$('clearApis').onclick=()=>{api={provider:'gemini',geminiKey:'',geminiModel:'gemini-3.8-flash',openrouterKey:'',openrouterModel:'deepseek/deepseek-r1',elevenKey:'',elevenVoice:''};saveApi();$('apiDialog').close();alert('Saved API keys cleared from this device.')};
$('newBtn').onclick=()=>{$('title').value='';$('topic').value='';$('transcript').textContent='';$('player').classList.add('hidden');$('title').focus()};
function script(){const topic=$('topic').value.trim()||'the strange things that happen after midnight',chars=cast.map(id=>db.characters.find(c=>c.id===id)).filter(Boolean),rounds=+$('length').value===5?7:+$('length').value===10?12:18,prompts=['What is your genuine first reaction to this?','What do people consistently misunderstand about it?','You clearly see it differently. What are they missing?','What personal experience shapes your view?','Push that idea further. What happens next?','What would actually change your mind?','Give me one belief you would defend even if everyone disagreed.'],lines=[`INTRO — Welcome to Nightcast. Tonight: ${topic}.`];for(let r=0;r<rounds;r++){chars.forEach((c,i)=>{const p=prompts[r%prompts.length],other=chars[(i-1+chars.length)%chars.length];lines.push(`${c.name}: ${p}${r?' Build on what '+other.name+' just said without repeating it.':''} Speak in your own personality and ${c.style||'natural'} style. ${c.catchphrase?'Use this catchphrase naturally only when it fits: '+c.catchphrase+'.':''}`)})}lines.push('OUTRO — That’s Nightcast. Until next time.');return lines}
function show(lines,title){current={id:crypto.randomUUID(),title:title||$('title').value||'Untitled Nightcast',topic:$('topic').value,format:$('format').value,tone:$('tone').value,created:new Date().toISOString(),lines,cast:[...cast]};$('title').value=current.title;$('transcript').textContent=lines.join('\n\n');$('player').classList.remove('hidden');$('speaker').textContent='Generated';$('line').textContent=current.title}
function generate(){show(script())}$('generate').onclick=generate;
function makePrompt(){const chars=cast.map(id=>db.characters.find(c=>c.id===id)).filter(Boolean);return `Create a ${$('length').value}-minute ${$('format').value} podcast in a ${$('tone').value} tone. Title: ${$('title').value||'Untitled Nightcast'}. Topic: ${$('topic').value||'a strange midnight mystery'}. Cast:\n${chars.map(c=>`Name: ${c.name}; Bio: ${c.bio}; Personality: ${c.personality}; Speaking style: ${c.style}; Catchphrase: ${c.catchphrase}`).join('\n')} Return natural multi-speaker lines as an array. Prefix every line with the speaker name.`}
async function generateOpenRouter(prompt){const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+api.openrouterKey,'HTTP-Referer':location.origin,'X-Title':'Nightcast Podcast'} ,body:JSON.stringify({model:api.openrouterModel||'deepseek/deepseek-r1',messages:[{role:'system',content:'You are Nightcast Podcast Director. Return only JSON with keys title and lines. lines is an array of natural multi-speaker dialogue.'},{role:'user',content:prompt}],temperature:.9,response_format:{type:'json_object'}})});const j=await r.json();if(!r.ok)throw Error(j?.error?.message||'OpenRouter request failed');const t=j?.choices?.[0]?.message?.content||'';return JSON.parse(t)}
async function generateGeminiDirect(prompt){const models=[api.geminiModel||'gemini-3.8-flash','gemini-3.8-flash','gemini-3.7-flash','gemini-3.6-flash','gemini-3.5-flash-lite'].filter((m,i,a)=>m&&a.indexOf(m)===i);let last='Gemini request failed';for(const model of models){const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':api.geminiKey},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],systemInstruction:{parts:[{text:'You are Nightcast Podcast Director. Return only JSON with keys title and lines. lines is an array of natural multi-speaker dialogue.'}]},generationConfig:{temperature:.9,maxOutputTokens:7000,responseMimeType:'application/json'}})});const j=await r.json();if(r.ok){const t=j?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';if(t)return JSON.parse(t)}last=j?.error?.message||last;if(![429,500,502,503,504].includes(r.status))break}throw Error(last)}
async function aiGenerate(){const provider=api.provider||'gemini';$('aiGenerate').disabled=true;$('aiGenerate').textContent='Generating…';try{const prompt=makePrompt();let j;if(provider==='local'){generate();return}if(provider==='openrouter'){if(!api.openrouterKey)throw Error('Add an OpenRouter API key in API Vault first.');j=await generateOpenRouter(prompt)}else{if(api.geminiKey)j=await generateGeminiDirect(prompt);else{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'generate',model:api.geminiModel,prompt})});const x=await r.json();if(!r.ok)throw Error(x.error||'Gemini failed');j=x}}show(j.lines||script(),j.title)}catch(e){alert(e.message+' — using the local podcast generator instead.');generate()}finally{$('aiGenerate').disabled=false;$('aiGenerate').textContent='✨ Generate with AI'}}
$('aiGenerate').onclick=aiGenerate;
let speaking=false;
async function speak(i=0){if(!current||i>=current.lines.length){speaking=false;return}speaking=true;const text=current.lines[i],m=text.match(/^([^—:]+)[—:]/),name=m?m[1].trim():'Nightcast',c=db.characters.find(x=>x.name===name);$('speaker').textContent=name;$('line').textContent=text.replace(/^([^—:]+)[—:]/,'').trim();const clean=text.replace(/^([^—:]+)[—:]/,'').trim();if(api.elevenKey&&api.elevenVoice){try{const r=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(api.elevenVoice)}`,{method:'POST',headers:{'Content-Type':'application/json','xi-api-key':api.elevenKey},body:JSON.stringify({text:clean,model_id:'eleven_multilingual_v2'})});if(r.ok){const blob=await r.blob(),url=URL.createObjectURL(blob),audio=new Audio(url);audio.onended=()=>{URL.revokeObjectURL(url);speak(i+1)};audio.onerror=()=>speak(i+1);audio.play();return}}catch{}}const u=new SpeechSynthesisUtterance(clean);if(c){u.rate=c.rate||.95;u.pitch=c.pitch??1;const v=speechSynthesis.getVoices().find(x=>x.name===c.voice);if(v)u.voice=v}u.onend=()=>speak(i+1);speechSynthesis.speak(u)}
$('play').onclick=()=>{speechSynthesis.cancel();speak()};$('stop').onclick=()=>{speechSynthesis.cancel();speaking=false};
$('save').onclick=()=>{if(!current)return;db.episodes.unshift(current);db.episodes=db.episodes.slice(0,100);persist()};
$('download').onclick=()=>{if(!current)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([current.lines.join('\n\n')],{type:'text/plain'}));a.download=(current.title||'nightcast').replace(/[^a-z0-9]+/gi,'-')+'.txt';a.click()};
$('gemini').onclick=()=>{if(!current)return;const chars=current.cast.map(id=>db.characters.find(c=>c.id===id)).filter(Boolean);const md=`# Nightcast Podcast Pack\n\n## Episode\nTitle: ${current.title}\nTopic: ${current.topic}\nFormat: ${current.format}\nTone: ${current.tone}\n\n## Cast\n${chars.map(c=>`### ${c.name}\nBio: ${c.bio}\nPersonality: ${c.personality}\nSpeaking style: ${c.style}`).join('\n\n')}\n\n## Transcript\n${current.lines.join('\n\n')}`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([md],{type:'text/markdown'}));a.download='nightcast-podcast-pack.md';a.click()};
function renderEpisodes(){$('episodeList').innerHTML=db.episodes.map((e,i)=>`<article class="card"><h3>${esc(e.title)}</h3><div class="meta">${new Date(e.created).toLocaleString()} · ${esc(e.format)} · ${esc(e.tone)}</div><p>${esc(e.topic||'')}</p><button onclick="loadEp(${i})">Open</button><button onclick="delEp(${i})">Delete</button></article>`).join('')||'<p>No saved episodes yet.</p>'}
window.loadEp=i=>{current=db.episodes[i];$('title').value=current.title;$('topic').value=current.topic||'';$('format').value=current.format||'Interview';$('tone').value=current.tone||'Natural';$('transcript').textContent=current.lines.join('\n\n');$('player').classList.remove('hidden')};window.delEp=i=>{db.episodes.splice(i,1);persist()};
$('exportAll').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='nightcast-podcast-library.json';a.click()};
$('charForm').onsubmit=e=>{e.preventDefault();const id=$('charId').value||crypto.randomUUID(),c={id,name:$('charName').value.trim(),bio:$('charBio').value,personality:$('charPersonality').value,style:$('charStyle').value,catchphrase:$('charCatch').value,voice:$('charVoice').value,rate:Number($('charRate').value)||.95,pitch:Number($('charPitch').value)||1};const n=db.characters.findIndex(x=>x.id===id);if(n<0)db.characters.push(c);else db.characters[n]=c;if(!cast.includes(id)&&cast.length<2)cast.push(id);$('charDialog').close();persist()};
$('previewVoice').onclick=()=>{const u=new SpeechSynthesisUtterance(`Hello. I am ${$('charName').value||'your podcast host'}.`);u.rate=Number($('charRate').value)||.95;u.pitch=Number($('charPitch').value)||1;speechSynthesis.cancel();speechSynthesis.speak(u)};
loadVoices();renderCast();renderEpisodes();