const CK='nightcast-characters-v2';
function cdb(){try{return JSON.parse(localStorage.getItem(CK)||'[]')}catch{return[]}}
function csave(a){localStorage.setItem(CK,JSON.stringify(a));db.characters=a.map(function(c){return{id:c.id,name:c.name,bio:c.description||'',personality:c.personality||'',style:c.speaking_style||'',catchphrase:c.catchphrase||'',voice:c.voice||'',rate:c.rate||.95,pitch:c.pitch==null?1:c.pitch,lore:c.lore||'',lorebooks:c.lorebooks||[]}});persist()}
function blankChar(){return{id:crypto.randomUUID(),name:'',creator:'',version:'',tags:[],avatar:'',summary:'',description:'',personality:'',scenario:'',first_mes:'',mes_example:'',alternate_greetings:[],creator_notes:'',system_prompt:'',post_history_instructions:'',speaking_style:'',catchphrase:'',lore:'',memory:'on',voice:'',rate:.95,pitch:1,lorebooks:[],extensions:{}}}
function norm(x){var d=x&& (x.data||x.character||x.character_data||x),c=blankChar();if(!d||typeof d!=='object')return c;function p(){for(var i=0;i<arguments.length;i++)if(d[arguments[i]]!=null)return d[arguments[i]];return ''}c.name=String(p('name','char_name','character_name'));c.creator=String(p('creator','author','creator_name'));c.version=String(p('character_version','version'));c.tags=Array.isArray(d.tags)?d.tags:String(p('tags')).split(',').map(function(s){return s.trim()}).filter(Boolean);c.avatar=String(p('avatar','avatar_url','image'));c.summary=String(p('summary','short_description','tagline'));c.description=String(p('description','long_description','context','persona','definition','char_persona'));c.personality=String(p('personality','traits'));c.scenario=String(p('scenario','context_scenario'));c.first_mes=String(p('first_mes','greeting','greeting_message','char_greeting','first_message'));c.mes_example=String(p('mes_example','example_dialogue','example_messages','example_chat'));c.alternate_greetings=Array.isArray(d.alternate_greetings)?d.alternate_greetings:String(p('alternate_greetings')).split(/\n+/).filter(Boolean);c.creator_notes=String(p('creator_notes','notes'));c.system_prompt=String(p('system_prompt','system'));c.post_history_instructions=String(p('post_history_instructions','post_history'));c.speaking_style=String(p('speaking_style','style','voice_style'));c.catchphrase=String(p('catchphrase'));c.lore=String(p('lore','background','backstory','world'));c.extensions=d.extensions&&typeof d.extensions==='object'?d.extensions:{};var book=d.character_book||d.characterBook||d.lorebook||d.world_info;if(book)c.lorebooks=[{name:book.name||'Embedded character book',url:'',data:book}];return c}
function openChar(c){$('charId').value=c.id;$('charName').value=c.name;$('charCreator').value=c.creator;$('charVersion').value=c.version;$('charTags').value=c.tags.join(', ');$('charAvatar').value=c.avatar;$('charSummary').value=c.summary;$('charBio').value=c.description;$('charPersonality').value=c.personality;$('charScenario').value=c.scenario;$('charGreeting').value=c.first_mes;$('charExamples').value=c.mes_example;$('charAltGreetings').value=c.alternate_greetings.join('\n');$('charCreatorNotes').value=c.creator_notes;$('charSystem').value=c.system_prompt;$('charPostHistory').value=c.post_history_instructions;$('charLore').value=c.lore;$('charStyle').value=c.speaking_style;$('charCatch').value=c.catchphrase;$('charMemory').value=c.memory||'on';$('charRate').value=c.rate||.95;$('charPitch').value=c.pitch==null?1:c.pitch;loadVoices(c.voice);$('charDialog').showModal();renderLoreSlots()}
function renderCharacters(){var a=cdb(),html='';a.forEach(function(c){html+='<article class="card"><div class="avatarMini">'+(c.avatar?'<img src="'+esc(c.avatar)+'" alt="">':'♢')+'</div><h3>'+esc(c.name||'Unnamed')+'</h3><div class="meta">'+esc((c.tags||[]).join(' · '))+'</div><p>'+esc(c.summary||c.description||'')+'</p><button onclick="editChar(\''+c.id+'\')">Edit</button><button onclick="useChar(\''+c.id+'\')">Use in Cast</button><button onclick="exportChar(\''+c.id+'\')">V2 JSON</button><button onclick="deleteChar(\''+c.id+'\')">Delete</button></article>'});$('characterList').innerHTML=html||'<p>No characters yet.</p>'}
window.editChar=function(id){openChar(cdb().find(function(c){return c.id===id})||blankChar())};window.useChar=function(id){if(!cast.includes(id))cast.push(id);renderCast();showView('studio')};window.deleteChar=function(id){if(confirm('Delete this character?')){csave(cdb().filter(function(c){return c.id!==id}));renderCharacters()}};
function exportData(c){var d={name:c.name,description:c.description,personality:c.personality,scenario:c.scenario,first_mes:c.first_mes,mes_example:c.mes_example,creator_notes:c.creator_notes,system_prompt:c.system_prompt,post_history_instructions:c.post_history_instructions,alternate_greetings:c.alternate_greetings,tags:c.tags,creator:c.creator,character_version:c.version,extensions:c.extensions};if(c.lorebooks&&c.lorebooks.length)d.character_book=c.lorebooks[0].data||{name:c.lorebooks[0].name||'Lorebook',entries:[]};return{spec:'chara_card_v2',spec_version:'2.0',data:d}}
window.exportChar=function(id){var c=cdb().find(function(x){return x.id===id});if(!c)return;var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(exportData(c),null,2)],{type:'application/json'}));a.download=(c.name||'character').replace(/[^a-z0-9]+/gi,'_')+'.json';a.click()};
$('newChar').onclick=function(){openChar(blankChar())};$('manageCast').onclick=function(){openChar(blankChar())};
function readFormChar(){var c=blankChar();c.id=$('charId').value||c.id;c.name=$('charName').value.trim();c.creator=$('charCreator').value;c.version=$('charVersion').value;c.tags=$('charTags').value.split(',').map(function(s){return s.trim()}).filter(Boolean);c.avatar=$('charAvatar').value;c.summary=$('charSummary').value;c.description=$('charBio').value;c.personality=$('charPersonality').value;c.scenario=$('charScenario').value;c.first_mes=$('charGreeting').value;c.mes_example=$('charExamples').value;c.alternate_greetings=$('charAltGreetings').value.split(/\n+/).filter(Boolean);c.creator_notes=$('charCreatorNotes').value;c.system_prompt=$('charSystem').value;c.post_history_instructions=$('charPostHistory').value;c.lore=$('charLore').value;c.speaking_style=$('charStyle').value;c.catchphrase=$('charCatch').value;c.voice=$('charVoice').value;c.rate=Number($('charRate').value)||.95;c.pitch=Number($('charPitch').value)||1;c.memory=$('charMemory').value;return c}
$('charForm').onsubmit=function(e){e.preventDefault();var c=readFormChar(),a=cdb(),i=a.findIndex(function(x){return x.id===c.id});if(i<0)a.push(c);else a[i]=c;csave(a);$('charDialog').close();renderCharacters()};
$('exportCharJson').onclick=function(){var c=readFormChar(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(exportData(c),null,2)],{type:'application/json'}));a.download=(c.name||'character').replace(/[^a-z0-9]+/gi,'_')+'.json';a.click()};
async function importObject(x,source){var c=norm(x),a=cdb(),i=a.findIndex(function(z){return z.id===c.id});if(i<0)a.push(c);else a[i]=c;csave(a);openChar(c);$('importStatus').textContent='Imported '+(c.name||'character')+(source?' from '+source:'')+'. Fields normalized into portable card format.';showView('characters');renderCharacters()}
async function importFile(f){$('importStatus').textContent='Reading '+f.name+'…';if(f.type==='image/png'||/\.png$/i.test(f.name)){var ab=await f.arrayBuffer(),u=new Uint8Array(ab),pos=8,found='';while(pos+12<u.length){var len=new DataView(ab,pos,4).getUint32(0),type=new TextDecoder().decode(u.slice(pos+4,pos+8));if(type==='tEXt'||type==='iTXt'){var s=new TextDecoder().decode(u.slice(pos+8,pos+8+len));if(s.includes('chara')||s.includes('ccv3'))found+=s+'\n'}pos+=12+len}var m=found.match(/(?:chara|ccv3)[^A-Za-z0-9+/=]*([A-Za-z0-9+/=]{80,})/);if(!m)throw Error('No embedded character card JSON was found in this PNG.');var raw=atob(m[1]),bytes=Uint8Array.from(raw,function(ch){return ch.charCodeAt(0)});return importObject(JSON.parse(new TextDecoder().decode(bytes)),f.name)}var text=await f.text();try{return importObject(JSON.parse(text),f.name)}catch(e){var c=blankChar();c.name=f.name.replace(/\.[^.]+$/,'');c.description=text.slice(0,50000);return importObject(c,f.name)}}
$('analyzeFile').onclick=async function(){var f=$('charFile').files&&$('charFile').files[0];if(!f)return alert('Choose a character card or export first.');try{await importFile(f)}catch(e){$('importStatus').textContent=e.message}};
$('crawlUrl').onclick=async function(){var url=$('importUrl').value.trim();if(!url)return;try{$('importStatus').textContent='Fetching public source…';var r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:url,type:'character'})}),j=await r.json();if(!r.ok)throw Error(j.error||'Import failed');await importObject(j.data,j.source)}catch(e){$('importStatus').textContent=e.message}};
function renderLoreSlots(){var c=cdb().find(function(x){return x.id===$('charId').value}),ls=(c&&c.lorebooks||[]).slice(0,3),html='';for(var i=0;i<3;i++)html+='<label>Lorebook '+(i+1)+'<input class="loreUrl" data-i="'+i+'" value="'+esc(ls[i]&&ls[i].url||'')+'" placeholder="https://chub.ai/... or public lorebook JSON URL"></label><div class="meta">'+esc(ls[i]&&ls[i].name||'')+'</div>';$('loreSlots').innerHTML=html}
$('saveLoreLinks').onclick=async function(){var id=$('charId').value;if(!id){$('loreStatus').textContent='Save the character first, then attach lorebooks.';return}var a=cdb(),c=a.find(function(x){return x.id===id});c.lorebooks=Array.from(document.querySelectorAll('.loreUrl')).map(function(x){return{url:x.value.trim(),name:'',entries:[]}}).filter(function(x){return x.url}).slice(0,3);csave(a);$('loreStatus').textContent='Saved up to 3 lorebook links to '+c.name+'.';for(var i=0;i<c.lorebooks.length;i++){try{var r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:c.lorebooks[i].url,type:'lorebook'})}),j=await r.json();if(r.ok){c.lorebooks[i].data=j.data||j.text;c.lorebooks[i].name=(j.data&&j.data.name)||c.lorebooks[i].name}}catch(e){}}csave(a);$('loreStatus').textContent='Lorebook links saved. Public sources were fetched where accessible.'};
function showView(v){['studio','characters','import'].forEach(function(x){$(x+'View').classList.toggle('hidden',x!==v)});document.querySelectorAll('.tab').forEach(function(b){b.classList.toggle('active',b.dataset.view===v)});if(v==='characters')renderCharacters();if(v==='import')renderLoreSlots()}
document.querySelectorAll('.tab').forEach(function(b){b.onclick=function(){showView(b.dataset.view)}});$('previewVoice').onclick=function(){var u=new SpeechSynthesisUtterance('Hello. I am '+($('charName').value||'your podcast character')+'.');u.rate=Number($('charRate').value)||.95;u.pitch=Number($('charPitch').value)||1;speechSynthesis.cancel();speechSynthesis.speak(u)};renderCharacters();