(()=>{
const K='nightcast-free-voice-v1';
const voices=[
 ['af_heart','Kokoro · Heart · American female'],['af_bella','Kokoro · Bella · American female'],['af_nicole','Kokoro · Nicole · American female'],['af_sarah','Kokoro · Sarah · American female'],['af_nova','Kokoro · Nova · American female'],['af_kore','Kokoro · Kore · American female'],['af_aoede','Kokoro · Aoede · American female'],['af_alloy','Kokoro · Alloy · American female'],['af_river','Kokoro · River · American female'],['af_sky','Kokoro · Sky · American female'],
 ['am_fenrir','Kokoro · Fenrir · American male'],['am_michael','Kokoro · Michael · American male'],['am_onyx','Kokoro · Onyx · American male'],['am_puck','Kokoro · Puck · American male'],['am_echo','Kokoro · Echo · American male'],['am_eric','Kokoro · Eric · American male'],['am_liam','Kokoro · Liam · American male'],['am_adam','Kokoro · Adam · American male'],
 ['bf_emma','Kokoro · Emma · British female'],['bf_isabella','Kokoro · Isabella · British female'],['bf_lily','Kokoro · Lily · British female'],['bf_alice','Kokoro · Alice · British female'],['bm_george','Kokoro · George · British male'],['bm_fable','Kokoro · Fable · British male'],['bm_daniel','Kokoro · Daniel · British male'],['bm_lewis','Kokoro · Lewis · British male']
];
let tts=null,loading=null,audio=null,token=0;
function settings(){try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return{}}}
function saveSettings(x){localStorage.setItem(K,JSON.stringify(x))}
async function getTTS(){if(tts)return tts;if(loading)return loading;loading=(async()=>{const mod=await import('https://cdn.jsdelivr.net/npm/kokoro-js@1.2.1/+esm');const C=mod.KokoroTTS||mod.default?.KokoroTTS;if(!C)throw Error('Kokoro library could not load.');const device='gpu' in navigator?'webgpu':'wasm';tts=await C.from_pretrained('onnx-community/Kokoro-82M-v1.0-ONNX',{dtype:device==='webgpu'?'fp32':'q4f16',device});return tts})();try{return await loading}finally{loading=null}}
function wavBlob(samples,rate){const int16=new Int16Array(samples.length);for(let i=0;i<samples.length;i++)int16[i]=Math.max(-1,Math.min(1,samples[i]))*32767;const b=new ArrayBuffer(44+int16.length*2),v=new DataView(b);v.setUint32(0,0x46464952,true);v.setUint32(4,36+int16.length*2,true);v.setUint32(8,0x45564157,true);v.setUint32(12,0x20746d66,true);v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);v.setUint32(36,0x61746164,true);v.setUint32(40,int16.length*2,true);for(let i=0;i<int16.length;i++)v.setInt16(44+i*2,int16[i],true);return new Blob([b],{type:'audio/wav'})}
async function speak(text,voice,speed=1){const id=++token;if(audio){try{audio.pause()}catch{};try{URL.revokeObjectURL(audio.src)}catch{};audio=null}const engine=await getTTS();if(id!==token)throw Error('cancelled');const out=await engine.generate(text,{voice:voice||'af_heart',speed});if(id!==token)throw Error('cancelled');const samples=out.audio||out.data,rate=out.sampling_rate||out.sample_rate||24000,url=URL.createObjectURL(wavBlob(samples,rate));audio=new Audio(url);return new Promise((resolve,reject)=>{audio.onended=()=>{URL.revokeObjectURL(url);audio=null;resolve()};audio.onerror=e=>{URL.revokeObjectURL(url);audio=null;reject(e)};audio.play().catch(reject)})}
function addOptions(){const s=document.getElementById('charVoice');if(!s)return;const old=s.value;for(const [id,label] of voices){if(![...s.options].some(o=>o.value==='KO:'+id)){const o=document.createElement('option');o.value='KO:'+id;o.textContent=label;s.appendChild(o)}}if(old)s.value=old}
function patchPreview(){const b=document.getElementById('previewVoice');if(!b||b.dataset.freePatched)return;b.dataset.freePatched='1';b.addEventListener('click',async()=>{const v=document.getElementById('charVoice')?.value||'';if(!v.startsWith('KO:'))return;const text='Hello. I am '+(document.getElementById('charName')?.value||'your Nightcast character')+'. This is my free neural voice preview.';b.disabled=true;b.textContent='Loading Kokoro…';try{await speak(text,v.slice(3),Number(document.getElementById('charRate')?.value)||1)}catch(e){if(e.message!=='cancelled')alert('Kokoro voice preview failed: '+e.message)}finally{b.disabled=false;b.textContent='Preview Voice'}})}
const oldSpeak=window.ncSpeak;
window.ncSpeak=async function(i=0){if(!current||i>=current.lines.length){return}const raw=current.lines[i],line=typeof raw==='string'?raw:String(raw?.text||raw?.content||''),m=line.match(/^\s*([^—:\n]+)\s*[—:]/),name=m?m[1].trim():'Nightcast',c=db.characters.find(x=>String(x.name).toLowerCase()===name.toLowerCase())||db.characters.find(x=>String(x.name).toLowerCase().includes(name.toLowerCase()));$('speaker').textContent=name;$('line').textContent=line.replace(/^\s*([^—:\n]+)\s*[—:]/,'').trim();const text=$('line').textContent;if(!text)return window.ncSpeak(i+1);const v=String(c?.voice||'');if(v.startsWith('KO:')){try{await speak(text,v.slice(3),Number(c?.rate)||1);return window.ncSpeak(i+1)}catch(e){if(e.message==='cancelled')return;console.warn('Kokoro failed, falling back to ElevenLabs/browser TTS',e)}}return oldSpeak?oldSpeak(i):undefined};
const oldStop=document.getElementById('stop');if(oldStop){oldStop.addEventListener('click',()=>{token++;if(audio){try{audio.pause()}catch{};try{URL.revokeObjectURL(audio.src)}catch{};audio=null}})}
const obs=new MutationObserver(()=>{addOptions();patchPreview()});obs.observe(document.body,{childList:true,subtree:true});addOptions();patchPreview();
window.NightcastFreeVoices={voices,getTTS,speak};
})();