(()=>{
const $=id=>document.getElementById(id),VK='nightcast-voices-v1';
let voices=JSON.parse(localStorage.getItem(VK)||'[]');
const save=()=>localStorage.setItem(VK,JSON.stringify(voices));
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
async function previewVoice(id,text='This is a Nightcast voice preview.'){
 const key=api?.elevenKey;if(!key||!id){alert('Add your ElevenLabs API key and select an ElevenLabs voice first.');return}
 try{const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,voiceId:String(id).replace(/^EL:/,''),apiKey:key,modelId:'eleven_v3'})});if(!r.ok){let j={};try{j=await r.json()}catch{}throw Error(j.error||'ElevenLabs preview failed')}const a=new Audio(URL.createObjectURL(await r.blob()));a.onended=()=>URL.revokeObjectURL(a.src);await a.play()}catch(e){alert(e.message)}}
async function cloneVoice(file,name,description){
 const key=api?.elevenKey;if(!key||!file){alert('Add your ElevenLabs API key and choose an audio sample first.');return}
 if(!file.type.startsWith('audio/')){alert('Please choose an audio file.');return}
 if(file.size>25*1024*1024){alert('Keep each sample under 25 MB for this browser upload.');return}
 const fd=new FormData();fd.append('files[]',file,file.name);fd.append('name',name||'Nightcast Voice Clone');if(description)fd.append('description',description);
 try{const r=await fetch('https://api.elevenlabs.io/v1/voices/add',{method:'POST',headers:{'xi-api-key':key},body:fd});const j=await r.json();if(!r.ok)throw Error(j?.detail?.message||j?.detail||j?.message||'Voice clone failed');if(!j.voice_id)throw Error('ElevenLabs did not return a voice ID.');voices.push({id:j.voice_id,name:name||'Nightcast Voice Clone',provider:'elevenlabs',type:'clone'});voices=[...new Map(voices.map(v=>[v.id,v])).values()];save();render();alert('Voice cloned and saved to Nightcast.');return j.voice_id}catch(e){alert(e.message+' If the browser blocks the request, use the ElevenLabs dashboard for cloning.')}
}
let recorder=null,recordChunks=[],recordStream=null;
function stopRecording(){try{recorder?.stop()}catch{};recordStream?.getTracks().forEach(t=>t.stop());recordStream=null}
function inject(){
 if($('voiceStudio'))return;
 const b=document.createElement('button');b.id='voiceStudio';b.className='secondary';b.textContent='🎙 Voice Studio';$('apiBtn').after(b);
 const d=document.createElement('dialog');d.id='voiceDialog';
 d.innerHTML='<form method="dialog" style="min-width:min(820px,94vw)"><h2>Voice Studio</h2><p>Browser voices are free. ElevenLabs adds natural voices, Voice Library, Voice Design, and voice cloning.</p><section class="importBox"><h3>🎨 Design a new voice</h3><label>Voice description<textarea id="voiceDesignDesc" placeholder="Deep, controlled male voice, refined American accent, calm menace, intimate pacing, subtle rasp."></textarea></label><label>Preview text<textarea id="voiceDesignText" placeholder="Paste preview text, or let ElevenLabs generate it."></textarea></label><button type="button" id="designVoice" class="primary">✨ Generate Voice Previews</button><div id="designStatus" class="status"></div><div id="voicePreviews" class="cards"></div></section><section class="importBox"><h3>🎙 Clone a voice</h3><p class="hint">Instant Voice Clone is intended for voices you have permission to clone. ElevenLabs recommends about 1–2 minutes of clean speech for a good quick clone.</p><label>Clone name<input id="cloneName" placeholder="Owen - Controlled Male"></label><label>Description<input id="cloneDesc" placeholder="Deep, controlled, intimate male voice"></label><label>Upload audio sample<input id="cloneFile" type="file" accept="audio/*"></label><button type="button" id="cloneUpload" class="primary">🧬 Clone Uploaded Voice</button><div id="recordStatus" class="status"></div><div class="row"><button type="button" id="recordStart" class="secondary">⏺ Start Recording</button><button type="button" id="recordStop" class="secondary" disabled>⏹ Stop & Clone</button></div></section><section class="importBox"><h3>🔑 Add an existing voice</h3><label>ElevenLabs voice ID<input id="voiceIdAdd" placeholder="Paste a voice ID"></label><label>Voice name<input id="voiceNameAdd" placeholder="Raven - Deep American"></label><button type="button" id="addVoice" class="primary">＋ Save Voice</button><button type="button" id="testAddedVoice" class="secondary">🔊 Test This Voice</button></section><section class="importBox"><button type="button" id="loadELVoices" class="secondary">🌐 Load ElevenLabs Voices</button><div id="elVoiceStatus" class="status"></div><div id="elVoices" class="cards"></div></section><section><h3>My Nightcast Voices</h3><div id="myVoices" class="cards"></div></section><button value="cancel">Close</button></form>';
 document.body.appendChild(d);b.onclick=()=>{render();d.showModal()};
 $('addVoice').onclick=()=>{const id=$('voiceIdAdd').value.trim();if(!id)return;voices.push({id,name:$('voiceNameAdd').value.trim()||id,provider:'elevenlabs'});voices=[...new Map(voices.map(v=>[v.id,v])).values()];save();render()};
 $('testAddedVoice').onclick=()=>previewVoice($('voiceIdAdd').value.trim(),prompt('Preview text','This is a Nightcast voice preview.')||'This is a Nightcast voice preview.');
 $('loadELVoices').onclick=loadEL;$('designVoice').onclick=designVoice;$('cloneUpload').onclick=async()=>{const f=$('cloneFile').files[0];if(!f){alert('Choose an audio sample first.');return}$('recordStatus').textContent='Cloning voice…';await cloneVoice(f,$('cloneName').value.trim(),$('cloneDesc').value.trim());$('recordStatus').textContent=''};
 $('recordStart').onclick=async()=>{try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Microphone recording is not available in this browser.');recordStream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];recorder=new MediaRecorder(recordStream);recorder.ondataavailable=e=>{if(e.data.size)recordChunks.push(e.data)};recorder.onstop=async()=>{const blob=new Blob(recordChunks,{type:recorder.mimeType||'audio/webm'});const f=new File([blob],'nightcast-recording.webm',{type:blob.type});$('recordStatus').textContent='Cloning recording…';await cloneVoice(f,$('cloneName').value.trim()||'Nightcast Recorded Voice',$('cloneDesc').value.trim());$('recordStatus').textContent=''};recorder.start();$('recordStart').disabled=true;$('recordStop').disabled=false;$('recordStatus').textContent='Recording…'}catch(e){alert(e.message)}};
 $('recordStop').onclick=()=>{stopRecording();$('recordStart').disabled=false;$('recordStop').disabled=true};
 const cf=$('charForm');if(cf&&!$('charVoicePreview')){const x=document.createElement('button');x.type='button';x.id='charVoicePreview';x.className='secondary';x.textContent='🔊 Preview Selected Voice';$('charVoice').after(x);x.onclick=()=>{const v=$('charVoice').value.trim();const text=prompt('Preview text','This is how this character will sound on Nightcast.')||'This is how this character will sound on Nightcast.';if(v.startsWith('EL:'))previewVoice(v,text);else{const u=new SpeechSynthesisUtterance(text),dv=speechSynthesis.getVoices().find(z=>z.name===v);if(dv)u.voice=dv;speechSynthesis.cancel();speechSynthesis.speak(u)}}}
 render();
}
function render(){if(!$('myVoices'))return;$('myVoices').innerHTML=voices.map((v,i)=>'<article class="card"><h3>'+esc(v.name)+'</h3><div class="meta">'+esc(v.provider)+' · '+esc(v.type||'library')+' · '+esc(v.id)+'</div><button onclick="ncPreviewVoice('+i+')">🔊 Preview</button><button onclick="ncUseVoice('+i+')">Use for Nightcast</button><button onclick="ncDeleteVoice('+i+')">Delete</button></article>').join('')||'<p>No saved external voices yet.</p>'}
window.ncPreviewVoice=i=>{const v=voices[i];if(v)previewVoice(v.id,prompt('Preview text','This is a Nightcast voice preview.')||'This is a Nightcast voice preview.')};window.ncDeleteVoice=i=>{voices.splice(i,1);save();render()};window.ncUseVoice=i=>{api.elevenVoice=voices[i].id;saveApi();alert('Voice set as the Nightcast default.')};
async function loadEL(){const key=api.elevenKey;if(!key){$('elVoiceStatus').textContent='Add your ElevenLabs API key in API Vault first.';return}$('elVoiceStatus').textContent='Loading voices…';try{const r=await fetch('https://api.elevenlabs.io/v2/voices?page_size=100',{headers:{'xi-api-key':key}}),j=await r.json();if(!r.ok)throw Error(j.detail?.message||j.message||'ElevenLabs voice request failed');const arr=j.voices||[];$('elVoices').innerHTML=arr.map(v=>'<article class="card"><h3>'+esc(v.name)+'</h3><div class="meta">'+esc(v.category||'')+' · '+esc(v.labels?.accent||'')+' · '+esc(v.labels?.gender||'')+'</div><p>'+esc(v.description||'')+'</p><button onclick="ncPickEL(\''+v.voice_id+'\',\''+String(v.name).replace(/'/g,"\\'")+'\')">＋ Add to Nightcast</button><button onclick="previewVoiceFromId(\''+v.voice_id+'\')">🔊 Preview</button></article>').join('');$('elVoiceStatus').textContent=arr.length+' voices loaded.'}catch(e){$('elVoiceStatus').textContent=e.message}}
window.previewVoiceFromId=id=>previewVoice(id,prompt('Preview text','This is a Nightcast voice preview.')||'This is a Nightcast voice preview.');window.ncPickEL=(id,name)=>{voices.push({id,name,provider:'elevenlabs',type:'library'});voices=[...new Map(voices.map(v=>[v.id,v])).values()];save();render()};
async function designVoice(){const key=api.elevenKey;if(!key){$('designStatus').textContent='Add your ElevenLabs API key in API Vault first.';return}const desc=$('voiceDesignDesc').value.trim(),text=$('voiceDesignText').value.trim();if(desc.length<20){$('designStatus').textContent='Give the voice a more detailed description first.';return}$('designStatus').textContent='Generating three voice candidates…';$('voicePreviews').innerHTML='';try{const r=await fetch('/api/voice-design',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:key,description:desc,text:text||undefined,autoGenerateText:!text})}),j=await r.json();if(!r.ok)throw Error(j.error||'Voice design failed');(j.previews||[]).forEach((p,i)=>{const a=document.createElement('article');a.className='card';a.innerHTML='<h3>Voice candidate '+(i+1)+'</h3><audio controls></audio><button class="primary">Save to Nightcast</button><button type="button" class="secondary">🔊 Play</button>';const audio=a.querySelector('audio');audio.src='data:'+String(p.media_type||'audio/mpeg')+';base64,'+p.audio_base_64;a.querySelectorAll('button')[1].onclick=()=>audio.play();a.querySelector('button').onclick=async()=>{const name=prompt('Name this voice',desc.slice(0,40))||'Nightcast Voice '+(i+1);const rr=await fetch('/api/voice-create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:key,name,description:desc,generatedVoiceId:p.generated_voice_id})}),jj=await rr.json();if(!rr.ok)alert(jj.error||'Could not save voice');else{voices.push({id:jj.voice_id,name,provider:'elevenlabs',type:'designed'});voices=[...new Map(voices.map(v=>[v.id,v])).values()];save();render();alert('Voice saved.')}};$('voicePreviews').appendChild(a)});$('designStatus').textContent=(j.previews||[]).length+' voice previews generated.'}catch(e){$('designStatus').textContent=e.message}}
inject();
})();