(()=>{
const $=id=>document.getElementById(id),VK='nightcast-voices-v1';
let voices=JSON.parse(localStorage.getItem(VK)||'[]');
function save(){localStorage.setItem(VK,JSON.stringify(voices))}
function esc2(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function inject(){if($('voiceStudio'))return;const b=document.createElement('button');b.id='voiceStudio';b.className='secondary';b.textContent='🎙 Voice Studio';$('apiBtn').after(b);const d=document.createElement('dialog');d.id='voiceDialog';d.innerHTML='<form method="dialog" style="min-width:min(720px,92vw)"><h2>Voice Studio</h2><p>Use browser voices for free, or connect ElevenLabs for much more natural character voices. ElevenLabs supports Voice Library, generated voices and clones.</p><div class="importBox"><label>ElevenLabs voice ID<input id="voiceIdAdd" placeholder="Paste a voice ID"></label><label>Voice name<input id="voiceNameAdd" placeholder="Raven - Deep American"></label><button type="button" id="addVoice" class="primary">＋ Save Voice</button></div><div class="importBox"><button type="button" id="loadELVoices" class="secondary">🌐 Load ElevenLabs Voices</button><div id="elVoiceStatus" class="status"></div><div id="elVoices" class="cards"></div></div><div><h3>My Nightcast Voices</h3><div id="myVoices" class="cards"></div></div><button value="cancel">Close</button></form>';document.body.appendChild(d);b.onclick=()=>{render();d.showModal()};$('addVoice').onclick=()=>{const id=$('voiceIdAdd').value.trim();if(!id)return;voices.push({id,name:$('voiceNameAdd').value.trim()||id,provider:'elevenlabs'});save();render()};$('loadELVoices').onclick=loadEL;render()}
function render(){if(!$('myVoices'))return;$('myVoices').innerHTML=voices.map((v,i)=>'<article class="card"><h3>'+esc2(v.name)+'</h3><div class="meta">'+esc2(v.provider)+' · '+esc2(v.id)+'</div><button onclick="ncUseVoice('+i+')">Use as default</button><button onclick="ncDeleteVoice('+i+')">Delete</button></article>').join('')||'<p>No saved external voices yet.</p>'}
window.ncDeleteVoice=i=>{voices.splice(i,1);save();render()};window.ncUseVoice=i=>{api.elevenVoice=voices[i].id;api.provider='gemini';saveApi();alert('Voice saved as the Nightcast ElevenLabs voice. It will be used when ElevenLabs is enabled.')};
async function loadEL(){const key=api.elevenKey;if(!key){$('elVoiceStatus').textContent='Add your ElevenLabs API key in API Vault first.';return}$('elVoiceStatus').textContent='Loading voices…';try{const r=await fetch('https://api.elevenlabs.io/v2/voices?page_size=100',{headers:{'xi-api-key':key}}),j=await r.json();if(!r.ok)throw Error(j.detail?.message||j.message||'ElevenLabs voice request failed');const arr=j.voices||[];$('elVoices').innerHTML=arr.map(v=>'<article class="card"><h3>'+esc2(v.name)+'</h3><div class="meta">'+esc2(v.category||'')+' · '+esc2(v.labels?.accent||'')+' · '+esc2(v.labels?.gender||'')+'</div><p>'+esc2(v.description||'')+'</p><button onclick="ncPickEL(\''+v.voice_id+'\',\''+String(v.name).replace(/'/g,"\\'")+'\')">＋ Add to Nightcast</button></article>').join('');$('elVoiceStatus').textContent=arr.length+' voices loaded.'}catch(e){$('elVoiceStatus').textContent=e.message}}
window.ncPickEL=(id,name)=>{voices.push({id,name,provider:'elevenlabs'});voices=[...new Map(voices.map(v=>[v.id,v])).values()];save();render()};inject();
})();