(()=>{
'use strict';
const $=id=>document.getElementById(id);
const DBKEY='nightcast-v3';
const db=()=>{try{return JSON.parse(localStorage.getItem(DBKEY)||'null')||{characters:[],episodes:[]}}catch{return{characters:[],episodes:[]}}};
function castNow(d){return [...document.querySelectorAll('#cast .castItem button')].map(b=>{const m=(b.getAttribute('onclick')||'').match(/removeCast\(['\"]([^'\"]+)/);return m&&m[1]}).filter(Boolean).map(id=>d.characters.find(c=>c.id===id)).filter(Boolean)}
function promptForAI(){const d=db(),topic=$('topic')?.value.trim()||'the supplied source material',mins=Number($('length')?.value||5),tone=$('tone')?.value||'Natural',format=$('format')?.value||'Interview',cast=castNow(d);return `NIGHTCAST PRODUCTION BRIEF\nFORMAT: ${format}\nTARGET: ${mins} minutes\nTONE: ${tone}\nTOPIC: ${topic}\n\nCAST:\n${cast.map(c=>`NAME: ${c.name}\nBIO: ${c.bio||''}\nPERSONALITY: ${c.personality||''}\nSPEAKING STYLE: ${c.style||''}\nCATCHPHRASE: ${c.catchphrase||''}\nLORE: ${c.lore||''}\nMEMORY: ${c.memory?(c.lastMemory||'none retained'):'disabled'}`).join('\n\n')||'Use the selected cast.'}\n\nSOURCE / USER PROMPT:\n${$('generatedPrompt')?.value||$('topic')?.value||''}\n\nDIALOGUE RULES:\nThe Host moves the conversation forward. Guests answer the actual question rather than repeating it. Characters react to specific things other speakers just said. Allow disagreement, interruption, humor, tension, uncertainty, callbacks and revelations. Do not make every character agree. Do not read source material aloud. Do not repeat prompts, questions, instructions, or another speaker verbatim. Every line must add something new. Keep voices distinct. Treat supplied fictional lore as canon; label uncertain material as theory. End naturally.`}
function addAIUI(){if($('aiControls'))return;const player=$('player');if(!player)return;const box=document.createElement('div');box.className='importBox';box.id='aiControls';box.innerHTML=`<h3>⚡ AI Generation</h3><p id="aiStatus">Local draft fallback is active. On Vercel, add <code>GEMINI_API_KEY</code> as a private environment variable for real AI generation.</p><div class="row"><button id="aiGenerate" class="primary">✨ Generate with AI</button><button id="jumpIn" class="secondary">🎙 Jump In</button></div><label id="audienceWrap" class="hidden">Your line<input id="audienceLine" placeholder="Say something to the cast…"></label>`;player.appendChild(box);
 $('aiGenerate').onclick=generateAI;$('jumpIn').onclick=()=>{const w=$('audienceWrap');w.classList.toggle('hidden');if(!w.classList.contains('hidden'))$('audienceLine').focus()};
 $('audienceLine').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.value.trim()){appendAudience(e.target.value.trim());e.target.value='';}})
}
function appendAudience(text){const cur=window.__nightcastCurrent;if(!cur)return alert('Generate an episode first.');cur.lines.push(`You: ${text}`);cur.lines.push(`Host: React naturally to the listener's comment and let the cast respond to the new information. Do not repeat the listener verbatim.`);$('transcript').textContent=cur.lines.join('\n\n');window.__nightcastCurrent=cur}
async function generateAI(){const status=$('aiStatus'),btn=$('aiGenerate');btn.disabled=true;status.textContent='Generating a real multi-speaker draft…';try{const r=await fetch('./api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'generate',prompt:promptForAI()})});const data=await r.json();if(!r.ok)throw Error(data.error||`AI endpoint returned ${r.status}`);const d=db(),cast=castNow(d),mins=Number($('length')?.value||5);let lines=Array.isArray(data.lines)?data.lines.filter(Boolean):[];if(!lines.length)throw Error('AI returned no dialogue lines.');const cur={id:crypto.randomUUID(),title:data.title||$('title').value||'Untitled Nightcast',topic:$('topic').value,format:$('format').value,tone:$('tone').value,length:mins,created:new Date().toISOString(),lines,cast:cast.map(c=>c.id),summary:data.summary||'',sourcePrompt:$('generatedPrompt')?.value||''};window.__nightcastCurrent=cur;$('title').value=cur.title;$('transcript').textContent=lines.join('\n\n');$('player').classList.remove('hidden');$('speaker').textContent='AI Generated';$('line').textContent=`${cur.title} · ${mins} min target`;status.textContent='AI episode ready. Use Play, Save, Download, or Gemini Podcast Pack.'}catch(e){status.textContent=`AI unavailable: ${e.message}. Use the normal Generate Podcast button for the free local fallback.`}finally{btn.disabled=false}}
function hook(){addAIUI();const g=$('generate');if(!g)return;g.textContent='Generate Local Fallback';g.onclick=()=>{const d=db(),cast=castNow(d);if(!cast.length)return alert('Add at least one character to the cast.');const mins=Number($('length').value)||5,topic=$('topic').value.trim()||'the strange things that happen after midnight',turns=Math.max(8,Math.round(mins*2)),qs=['What do you actually think about this?','What are people getting wrong?','What detail changes the picture?','How does this affect you personally?','What do you disagree with?','What are you not saying?','What happens if this gets worse?','What is the consequence nobody sees?'];const lines=[`INTRO — Welcome to Nightcast. Tonight we’re exploring: ${topic}.`];for(let i=0;i<turns;i++){const c=cast[i%cast.length];lines.push(`${c.name}: ${qs[i%qs.length]} [Local fallback: answer in your own voice; do not repeat the question. Add a specific reaction, detail, disagreement or revelation.]`)}lines.push('OUTRO — That’s Nightcast. Until next time.');const cur={id:crypto.randomUUID(),title:$('title').value||'Untitled Nightcast',topic,format:$('format').value,tone:$('tone').value,length:mins,created:new Date().toISOString(),lines,cast:cast.map(c=>c.id),sourcePrompt:$('generatedPrompt')?.value||''};window.__nightcastCurrent=cur;$('transcript').textContent=lines.join('\n\n');$('player').classList.remove('hidden');$('speaker').textContent='Local fallback';$('line').textContent=`${cur.title} · ${mins} min target`};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook);else hook();
})();
